//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight.WS.Server.Common.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ABS_Delivery_Item
    {
        public System.Guid ID { get; set; }
        public long SN { get; set; }
        public System.Guid DeliveryId { get; set; }
        public string Summary { get; set; }
        public System.Guid ObjectId { get; set; }
        public string ObjectName { get; set; }
        public string Units { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Counts { get; set; }
        public decimal Amount { get; set; }
    
        public virtual ABS_Delivery ABS_Delivery { get; set; }
        public virtual MasterData MasterData { get; set; }
    }
}
