//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight.WS.Server.Common.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplyInfo
    {
        public System.Guid ID { get; set; }
        public System.Guid MemberId { get; set; }
        public int Type { get; set; }
        public string Code { get; set; }
        public string OrderNo { get; set; }
        public string ProductName { get; set; }
        public string Pics { get; set; }
        public string Description { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string Status { get; set; }
    }
}
