//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight.WS.Server.Common.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BIZ_Pay_Record
    {
        public System.Guid ID { get; set; }
        public long SN { get; set; }
        public string TradeNo { get; set; }
        public int Business { get; set; }
        public Nullable<System.Guid> BusinessId { get; set; }
        public decimal Amount { get; set; }
        public int PayType { get; set; }
        public string Description { get; set; }
        public bool Payed { get; set; }
        public string Account { get; set; }
        public string Signature { get; set; }
        public System.Guid CreatorUserId { get; set; }
        public System.DateTime CreateTime { get; set; }
    }
}
