//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight.WS.Server.Common.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BIZ_Order
    {
        public System.Guid OID { get; set; }
        public long SN { get; set; }
        public string Code { get; set; }
        public string StageId { get; set; }
        public string MallCode { get; set; }
        public decimal OrderAmount { get; set; }
        public decimal FirstPay { get; set; }
        public Nullable<int> StageNum { get; set; }
        public Nullable<decimal> StageRate { get; set; }
        public bool FirstPayed { get; set; }
        public bool StagePayed { get; set; }
        public Nullable<System.Guid> AddressId { get; set; }
        public string InvoiceInfo { get; set; }
        public int InvoiceType { get; set; }
        public string LogisticsName { get; set; }
        public string LogisticsCode { get; set; }
        public Nullable<System.DateTime> OutDate { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CancelTime { get; set; }
    
        public virtual ABS_Contract ABS_Contract { get; set; }
        public virtual MDE_Member_Address MDE_Member_Address { get; set; }
    }
}
