//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight.WS.Server.Common.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckList
    {
        public System.Guid MID { get; set; }
        public System.Guid MemberId { get; set; }
        public string 客户类型 { get; set; }
        public string 手机号 { get; set; }
        public string 姓名 { get; set; }
        public string 身份证号 { get; set; }
        public string 工作单位_学校 { get; set; }
        public decimal 授信额度 { get; set; }
        public string 审核内容 { get; set; }
        public string 状态 { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int Status { get; set; }
        public Nullable<System.Guid> VerifyUserId { get; set; }
    }
}
