//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight.WS.Server.Common.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactInfo
    {
        public System.Guid ID { get; set; }
        public System.Guid MasterDataId { get; set; }
        public string Alias { get; set; }
        public string 联系方式 { get; set; }
        public string 号码 { get; set; }
        public bool 主要 { get; set; }
    }
}
