//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight.WS.Server.Common.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> ParentId { get; set; }
        public string 姓名 { get; set; }
        public string 任职部门 { get; set; }
        public string 职务 { get; set; }
        public string 生日 { get; set; }
        public string 登录 { get; set; }
        public string 登录帐号 { get; set; }
        public string 主要联系人 { get; set; }
        public string 电话号码 { get; set; }
        public string 移动电话 { get; set; }
        public string 电子邮件 { get; set; }
        public string 办公地点 { get; set; }
        public string 家庭住址 { get; set; }
        public string 备注 { get; set; }
    }
}
