//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight.WS.Server.Common.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> DeptId { get; set; }
        public byte[] Photo { get; set; }
        public string 姓名 { get; set; }
        public string 性别 { get; set; }
        public string 职位 { get; set; }
        public string 状态 { get; set; }
        public string 直接领导 { get; set; }
        public string 工号 { get; set; }
        public string 工种 { get; set; }
        public string 身份证号 { get; set; }
        public string 登录 { get; set; }
        public string 登录帐号 { get; set; }
        public string 电话号码 { get; set; }
        public string 移动电话 { get; set; }
        public string 电子邮件 { get; set; }
        public Nullable<System.DateTime> 入职日期 { get; set; }
        public Nullable<System.DateTime> 离职日期 { get; set; }
        public string 办公地点 { get; set; }
        public string 家庭住址 { get; set; }
        public string 备注 { get; set; }
    }
}
