//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight.WS.Server.Common.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MDG_Dictionary
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MDG_Dictionary()
        {
            this.ABS_Advance = new HashSet<ABS_Advance>();
            this.ABS_Clearing_Pay = new HashSet<ABS_Clearing_Pay>();
            this.ABS_Clearing_Pay1 = new HashSet<ABS_Clearing_Pay>();
            this.ABS_Contract_FundPlan = new HashSet<ABS_Contract_FundPlan>();
            this.ABS_StockDetail = new HashSet<ABS_StockDetail>();
            this.ABS_Storage_Location = new HashSet<ABS_Storage_Location>();
            this.ABS_Storage_Summary = new HashSet<ABS_Storage_Summary>();
            this.ImageData = new HashSet<ImageData>();
            this.MDE_Member_Address = new HashSet<MDE_Member_Address>();
            this.MDG_Customer = new HashSet<MDG_Customer>();
            this.MDG_Customer1 = new HashSet<MDG_Customer>();
            this.MDG_Customer2 = new HashSet<MDG_Customer>();
            this.MDG_Customer3 = new HashSet<MDG_Customer>();
            this.MDG_Customer4 = new HashSet<MDG_Customer>();
            this.MDG_Customer5 = new HashSet<MDG_Customer>();
            this.MDG_Employee = new HashSet<MDG_Employee>();
            this.MDG_Expense = new HashSet<MDG_Expense>();
            this.MDG_Material = new HashSet<MDG_Material>();
            this.MDG_Material1 = new HashSet<MDG_Material>();
            this.MDG_Material2 = new HashSet<MDG_Material>();
            this.MDG_Supplier = new HashSet<MDG_Supplier>();
            this.MDG_Supplier1 = new HashSet<MDG_Supplier>();
            this.MDG_Supplier2 = new HashSet<MDG_Supplier>();
            this.MDG_Supplier3 = new HashSet<MDG_Supplier>();
            this.MDS_Contact_Info = new HashSet<MDS_Contact_Info>();
        }
    
        public System.Guid MID { get; set; }
        public long SN { get; set; }
        public int Index { get; set; }
        public string Type { get; set; }
        public string Description { get; set; }
        public bool BuiltIn { get; set; }
        public bool Enable { get; set; }
        public Nullable<System.Guid> CreatorDeptId { get; set; }
        public System.Guid CreatorUserId { get; set; }
        public System.DateTime CreateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ABS_Advance> ABS_Advance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ABS_Clearing_Pay> ABS_Clearing_Pay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ABS_Clearing_Pay> ABS_Clearing_Pay1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ABS_Contract_FundPlan> ABS_Contract_FundPlan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ABS_StockDetail> ABS_StockDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ABS_Storage_Location> ABS_Storage_Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ABS_Storage_Summary> ABS_Storage_Summary { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImageData> ImageData { get; set; }
        public virtual MasterData MasterData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MDE_Member_Address> MDE_Member_Address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MDG_Customer> MDG_Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MDG_Customer> MDG_Customer1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MDG_Customer> MDG_Customer2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MDG_Customer> MDG_Customer3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MDG_Customer> MDG_Customer4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MDG_Customer> MDG_Customer5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MDG_Employee> MDG_Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MDG_Expense> MDG_Expense { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MDG_Material> MDG_Material { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MDG_Material> MDG_Material1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MDG_Material> MDG_Material2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MDG_Supplier> MDG_Supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MDG_Supplier> MDG_Supplier1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MDG_Supplier> MDG_Supplier2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MDG_Supplier> MDG_Supplier3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MDS_Contact_Info> MDS_Contact_Info { get; set; }
    }
}
