//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight.WS.Server.Common.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MDG_Customer
    {
        public System.Guid MID { get; set; }
        public long SN { get; set; }
        public Nullable<System.Guid> EnterpriseType { get; set; }
        public Nullable<System.Guid> IndustryType { get; set; }
        public string RegisterNumber { get; set; }
        public string TaxNumber { get; set; }
        public string Corporation { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
        public string BusinessScope { get; set; }
        public string Scale { get; set; }
        public Nullable<int> Staffs { get; set; }
        public Nullable<System.Guid> State { get; set; }
        public Nullable<System.Guid> Province { get; set; }
        public Nullable<System.Guid> City { get; set; }
        public Nullable<System.Guid> District { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string ZipCode { get; set; }
        public string Website { get; set; }
        public Nullable<System.Guid> Class { get; set; }
        public Nullable<System.Guid> Statu { get; set; }
        public string Description { get; set; }
        public bool Enable { get; set; }
        public bool Visible { get; set; }
        public Nullable<System.Guid> CreatorDeptId { get; set; }
        public System.Guid CreatorUserId { get; set; }
        public System.DateTime CreateTime { get; set; }
    
        public virtual BASE_Category BASE_Category { get; set; }
        public virtual BASE_Category BASE_Category1 { get; set; }
        public virtual MasterData MasterData { get; set; }
        public virtual MDG_Dictionary MDG_Dictionary { get; set; }
        public virtual MDG_Dictionary MDG_Dictionary1 { get; set; }
        public virtual MDG_Dictionary MDG_Dictionary2 { get; set; }
        public virtual MDG_Dictionary MDG_Dictionary3 { get; set; }
        public virtual MDG_Dictionary MDG_Dictionary4 { get; set; }
        public virtual MDG_Dictionary MDG_Dictionary5 { get; set; }
    }
}
