//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight.WS.Server.Common.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organization
    {
        public System.Guid ID { get; set; }
        public long SN { get; set; }
        public Nullable<System.Guid> ParentId { get; set; }
        public int NodeType { get; set; }
        public int Index { get; set; }
        public string 名称 { get; set; }
        public string 全称 { get; set; }
        public string 简称 { get; set; }
        public string 编码 { get; set; }
    }
}
