//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight.WS.Server.Common.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductExtend
    {
        public Nullable<System.Guid> ID { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> TypeId { get; set; }
        public int ExtendId { get; set; }
        public Nullable<int> Sort { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public string Site { get; set; }
    }
}
