//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight.WS.Server.Common.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleUser
    {
        public Nullable<System.Guid> ID { get; set; }
        public System.Guid RoleId { get; set; }
        public System.Guid UserId { get; set; }
        public string 用户名 { get; set; }
        public string 登录名 { get; set; }
        public string 描述 { get; set; }
        public string 状态 { get; set; }
    }
}
