//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight.WS.Server.Common.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SerialRecord
    {
        public Nullable<System.Guid> ID { get; set; }
        public System.Guid SchemeId { get; set; }
        public string 分组标识 { get; set; }
        public Nullable<int> 当前流水 { get; set; }
        public Nullable<int> 记录数 { get; set; }
        public Nullable<System.DateTime> 上次发生时间 { get; set; }
    }
}
