//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight.WS.Server.Common.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public System.Guid SupplierId { get; set; }
        public string 状态 { get; set; }
        public string 采购经理 { get; set; }
        public string 名称 { get; set; }
        public string 简称 { get; set; }
        public string 经营范围 { get; set; }
        public string 资产规模 { get; set; }
        public Nullable<int> 员工人数 { get; set; }
        public string 地址 { get; set; }
        public string 邮编 { get; set; }
    }
}
