//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight.WS.Server.Common.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_Alert_Send
    {
        public System.Guid ID { get; set; }
        public long SN { get; set; }
        public System.Guid MessageId { get; set; }
        public Nullable<System.Guid> TargetId { get; set; }
        public Nullable<int> SendType { get; set; }
        public string Target { get; set; }
        public Nullable<int> Times { get; set; }
        public Nullable<System.DateTime> SendTime { get; set; }
        public int Status { get; set; }
    
        public virtual SYS_Alert_Message SYS_Alert_Message { get; set; }
    }
}
