//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight.WS.Server.Common.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PREPARE_DOC
    {
        public System.Guid ID { get; set; }
        public string OrderNo { get; set; }
        public System.Guid MemberId { get; set; }
        public string MemberName { get; set; }
        public string MemberIdNumber { get; set; }
        public string MemberSource { get; set; }
        public string ProductTypeName { get; set; }
        public string ProductName { get; set; }
        public decimal Price { get; set; }
        public decimal Counts { get; set; }
        public decimal OrderAmount { get; set; }
        public decimal FirstPay { get; set; }
        public string memberPhone { get; set; }
        public string memberCode { get; set; }
        public string memberAddress { get; set; }
        public string ProductImage { get; set; }
        public Nullable<System.DateTime> OutDate { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<int> StageNum { get; set; }
        public int Status { get; set; }
        public string memberCardNo { get; set; }
        public int InvoiceType { get; set; }
        public string InvoiceInfo { get; set; }
        public Nullable<double> ProductCommissionRate { get; set; }
        public string ProductCode { get; set; }
        public string StatusName { get; set; }
    }
}
