//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight.WS.Server.Common.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_REFUNDMENTS
    {
        public System.Guid ID { get; set; }
        public string OrderNo { get; set; }
        public string ProductName { get; set; }
        public decimal Price { get; set; }
        public decimal Counts { get; set; }
        public System.Guid MemberId { get; set; }
        public string MemberName { get; set; }
        public decimal FirstPay { get; set; }
        public string MemberPhone { get; set; }
        public Nullable<System.Guid> ParentId { get; set; }
        public Nullable<System.Guid> RefundId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> PerformAmount { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> StageNum { get; set; }
        public int Status { get; set; }
        public Nullable<System.Guid> PlanId { get; set; }
        public string StatusName { get; set; }
        public string Title { get; set; }
    }
}
