//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight.WS.Server.Common.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class WithdrawalList
    {
        public System.Guid ID { get; set; }
        public string OrderId { get; set; }
        public string 客户姓名 { get; set; }
        public string 手机号 { get; set; }
        public string 开户银行 { get; set; }
        public string 银行卡号 { get; set; }
        public decimal 提现金额 { get; set; }
        public string 用途 { get; set; }
        public int 分期 { get; set; }
        public string 操作员 { get; set; }
        public Nullable<System.DateTime> 操作日期 { get; set; }
        public string 状态 { get; set; }
        public System.DateTime CreateTime { get; set; }
    }
}
