//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight.WS.Server.Common.ORM
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(ABS_Clearing))]
    [KnownType(typeof(ImageData))]
    
    public partial class ABS_Clearing_Attachs
    {
    	[DataMember]
        public System.Guid ID { get; set; }
    	[DataMember]
        public long SN { get; set; }
    	[DataMember]
        public System.Guid ClearingId { get; set; }
    	[DataMember]
        public System.Guid ImageId { get; set; }
    
    	[DataMember]
        public virtual ABS_Clearing ABS_Clearing { get; set; }
    	[DataMember]
        public virtual ImageData ImageData { get; set; }
    }
}
