//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight.WS.Server.Common.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ABS_Advance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ABS_Advance()
        {
            this.ABS_Advance_Detail = new HashSet<ABS_Advance_Detail>();
        }
    
        public System.Guid ID { get; set; }
        public long SN { get; set; }
        public string AccountNo { get; set; }
        public Nullable<System.Guid> CardType { get; set; }
        public System.Guid OwnerId { get; set; }
        public int Status { get; set; }
        public string Description { get; set; }
        public System.Guid CreatorDeptId { get; set; }
        public System.Guid CreatorUserId { get; set; }
        public System.DateTime CreateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ABS_Advance_Detail> ABS_Advance_Detail { get; set; }
        public virtual MDG_Dictionary MDG_Dictionary { get; set; }
        public virtual SYS_Organization SYS_Organization { get; set; }
        public virtual SYS_User SYS_User { get; set; }
        public virtual MasterData MasterData { get; set; }
    }
}
