//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight.WS.Server.Common.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ABS_Contract
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ABS_Contract()
        {
            this.ABS_Contract_Subjects = new HashSet<ABS_Contract_Subjects>();
            this.ABS_Contract_Attachs = new HashSet<ABS_Contract_Attachs>();
            this.ABS_Contract_FundPlan = new HashSet<ABS_Contract_FundPlan>();
        }
    
        public System.Guid ID { get; set; }
        public long SN { get; set; }
        public Nullable<System.Guid> ParentId { get; set; }
        public string ContractCode { get; set; }
        public string Title { get; set; }
        public System.Guid ObjectId { get; set; }
        public string ObjectName { get; set; }
        public Nullable<System.Guid> AgentId { get; set; }
        public string AgentName { get; set; }
        public Nullable<System.Guid> ExecuteDeptId { get; set; }
        public Nullable<System.Guid> ExecuteUserId { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<System.DateTime> InvalidDate { get; set; }
        public string Description { get; set; }
        public int Status { get; set; }
        public Nullable<System.Guid> CreatorDeptId { get; set; }
        public System.Guid CreatorUserId { get; set; }
        public System.DateTime CreateTime { get; set; }
    
        public virtual MasterData MasterData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ABS_Contract_Subjects> ABS_Contract_Subjects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ABS_Contract_Attachs> ABS_Contract_Attachs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ABS_Contract_FundPlan> ABS_Contract_FundPlan { get; set; }
        public virtual SYS_Organization SYS_Organization { get; set; }
        public virtual SYS_User SYS_User { get; set; }
        public virtual SYS_Organization SYS_Organization1 { get; set; }
        public virtual MDG_Employee MDG_Employee { get; set; }
        public virtual MasterData MasterData1 { get; set; }
    }
}
