//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight.WS.Server.Common.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ABS_Storage_Detail
    {
        public System.Guid ID { get; set; }
        public long SN { get; set; }
        public System.Guid SummaryId { get; set; }
        public Nullable<System.Guid> LocationId { get; set; }
        public int BatchNumber { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Counts { get; set; }
    
        public virtual ABS_Storage_Location ABS_Storage_Location { get; set; }
        public virtual ABS_Storage_Summary ABS_Storage_Summary { get; set; }
    }
}
