//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight.WS.Server.Common.ORM
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(ABS_Contract_GoodsPerform))]
    [KnownType(typeof(SYS_Organization))]
    [KnownType(typeof(SYS_User))]
    [KnownType(typeof(ABS_Delivery_Item))]
    [KnownType(typeof(ABS_Delivery_Attachs))]
    [KnownType(typeof(ABS_Storage_Location))]
    [KnownType(typeof(MasterData))]
    
    public partial class ABS_Delivery
    {
        public ABS_Delivery()
        {
            this.ABS_Contract_GoodsPerform = new HashSet<ABS_Contract_GoodsPerform>();
            this.ABS_Delivery_Item = new HashSet<ABS_Delivery_Item>();
            this.ABS_Delivery_Attachs = new HashSet<ABS_Delivery_Attachs>();
        }
    
    	[DataMember]
        public System.Guid ID { get; set; }
    	[DataMember]
        public long SN { get; set; }
    	[DataMember]
        public int Direction { get; set; }
    	[DataMember]
        public string ReceiptCode { get; set; }
    	[DataMember]
        public string HashCode { get; set; }
    	[DataMember]
        public Nullable<System.Guid> LocationId { get; set; }
    	[DataMember]
        public Nullable<System.Guid> ObjectId { get; set; }
    	[DataMember]
        public string ObjectName { get; set; }
    	[DataMember]
        public int PrintTimes { get; set; }
    	[DataMember]
        public string Description { get; set; }
    	[DataMember]
        public bool Validity { get; set; }
    	[DataMember]
        public System.Guid CreatorDeptId { get; set; }
    	[DataMember]
        public System.Guid CreatorUserId { get; set; }
    	[DataMember]
        public System.DateTime CreateTime { get; set; }
    
    	[DataMember]
        public virtual ICollection<ABS_Contract_GoodsPerform> ABS_Contract_GoodsPerform { get; set; }
    	[DataMember]
        public virtual SYS_Organization SYS_Organization { get; set; }
    	[DataMember]
        public virtual SYS_User SYS_User { get; set; }
    	[DataMember]
        public virtual ICollection<ABS_Delivery_Item> ABS_Delivery_Item { get; set; }
    	[DataMember]
        public virtual ICollection<ABS_Delivery_Attachs> ABS_Delivery_Attachs { get; set; }
    	[DataMember]
        public virtual ABS_Storage_Location ABS_Storage_Location { get; set; }
    	[DataMember]
        public virtual MasterData MasterData { get; set; }
    }
}
