//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight.WS.Server.Common.ORM
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(ABS_Clearing_Pay))]
    [KnownType(typeof(ABS_StockCapital))]
    [KnownType(typeof(MDG_Dictionary))]
    
    public partial class ABS_StockDetail
    {
    	[DataMember]
        public System.Guid ID { get; set; }
    	[DataMember]
        public long SN { get; set; }
    	[DataMember]
        public System.Guid CapitalId { get; set; }
    	[DataMember]
        public Nullable<System.Guid> ClearingId { get; set; }
    	[DataMember]
        public Nullable<System.Guid> AccountId { get; set; }
    	[DataMember]
        public decimal Amount { get; set; }
    
    	[DataMember]
        public virtual ABS_Clearing_Pay ABS_Clearing_Pay { get; set; }
    	[DataMember]
        public virtual ABS_StockCapital ABS_StockCapital { get; set; }
    	[DataMember]
        public virtual MDG_Dictionary MDG_Dictionary { get; set; }
    }
}
