//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight.WS.Server.Common.ORM
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(ABS_Contract_Subjects))]
    
    public partial class BIZ_Product_Snapshot
    {
    	[DataMember]
        public System.Guid SID { get; set; }
    	[DataMember]
        public long SN { get; set; }
    	[DataMember]
        public string ProductName { get; set; }
    	[DataMember]
        public string ProductSpeci { get; set; }
    	[DataMember]
        public Nullable<decimal> ProductPrice { get; set; }
    	[DataMember]
        public string ProductImage { get; set; }
    	[DataMember]
        public string Parameter { get; set; }
    	[DataMember]
        public string PackingList { get; set; }
    	[DataMember]
        public string Description { get; set; }
    	[DataMember]
        public string ProductPic1 { get; set; }
    	[DataMember]
        public string ProductPic2 { get; set; }
    	[DataMember]
        public string ProductPic3 { get; set; }
    	[DataMember]
        public string ProductPic4 { get; set; }
    	[DataMember]
        public string ProductPic5 { get; set; }
    	[DataMember]
        public System.DateTime CreateTime { get; set; }
    
    	[DataMember]
        public virtual ABS_Contract_Subjects ABS_Contract_Subjects { get; set; }
    }
}
