//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight.WS.Server.Common.ORM
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(ABS_Contract))]
    [KnownType(typeof(MDG_Dictionary))]
    [KnownType(typeof(SYS_User))]
    [KnownType(typeof(BIZ_Travel_Plan))]
    
    public partial class BIZ_Travel_Apply
    {
        public BIZ_Travel_Apply()
        {
            this.BIZ_Travel_Plan = new HashSet<BIZ_Travel_Plan>();
        }
    
    	[DataMember]
        public System.Guid CID { get; set; }
    	[DataMember]
        public long SN { get; set; }
    	[DataMember]
        public int TravelType { get; set; }
    	[DataMember]
        public string Destination { get; set; }
    	[DataMember]
        public Nullable<decimal> Budget { get; set; }
    	[DataMember]
        public Nullable<System.Guid> PayType { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> TicketTime { get; set; }
    	[DataMember]
        public Nullable<System.Guid> TicketUserId { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> TakeTime { get; set; }
    	[DataMember]
        public string Description { get; set; }
    	[DataMember]
        public Nullable<int> Status { get; set; }
    
    	[DataMember]
        public virtual ABS_Contract ABS_Contract { get; set; }
    	[DataMember]
        public virtual MDG_Dictionary MDG_Dictionary { get; set; }
    	[DataMember]
        public virtual SYS_User SYS_User { get; set; }
    	[DataMember]
        public virtual ICollection<BIZ_Travel_Plan> BIZ_Travel_Plan { get; set; }
    }
}
