//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight.WS.Server.Common.ORM
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(BIZ_Travel_Apply))]
    [KnownType(typeof(MDG_Dictionary))]
    
    public partial class BIZ_Travel_Plan
    {
    	[DataMember]
        public System.Guid ID { get; set; }
    	[DataMember]
        public long SN { get; set; }
    	[DataMember]
        public System.Guid TravelId { get; set; }
    	[DataMember]
        public string Starting { get; set; }
    	[DataMember]
        public string Destination { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> StartingTime { get; set; }
    	[DataMember]
        public Nullable<System.Guid> Vehicle { get; set; }
    	[DataMember]
        public Nullable<bool> NeedTicket { get; set; }
    	[DataMember]
        public string Description { get; set; }
    	[DataMember]
        public string Trains { get; set; }
    	[DataMember]
        public Nullable<decimal> Fare { get; set; }
    	[DataMember]
        public Nullable<int> GetTicket { get; set; }
    
    	[DataMember]
        public virtual BIZ_Travel_Apply BIZ_Travel_Apply { get; set; }
    	[DataMember]
        public virtual MDG_Dictionary MDG_Dictionary { get; set; }
    }
}
