//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight.WS.Server.Common.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class MDD_Numeric
    {
        public System.Guid ID { get; set; }
        public long SN { get; set; }
        public System.Guid MasterDataId { get; set; }
        public System.Guid PropertyId { get; set; }
        public Nullable<decimal> Value { get; set; }
    
        public virtual MasterData MasterData { get; set; }
        public virtual MasterData_Property MasterData_Property { get; set; }
    }
}
