//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight.WS.Server.Common.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class MDG_Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MDG_Employee()
        {
            this.ABS_Contract = new HashSet<ABS_Contract>();
            this.MDG_Employee1 = new HashSet<MDG_Employee>();
            this.MDR_ET = new HashSet<MDR_ET>();
        }
    
        public System.Guid MID { get; set; }
        public long SN { get; set; }
        public Nullable<int> Gender { get; set; }
        public Nullable<System.Guid> WorkType { get; set; }
        public string IdCardNo { get; set; }
        public Nullable<System.Guid> DirectLeader { get; set; }
        public string OfficeAddress { get; set; }
        public string HomeAddress { get; set; }
        public byte[] Photo { get; set; }
        public byte[] Thumbnail { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> DimissionDate { get; set; }
        public string Description { get; set; }
        public int Status { get; set; }
        public bool LoginUser { get; set; }
        public Nullable<System.Guid> CreatorDeptId { get; set; }
        public System.Guid CreatorUserId { get; set; }
        public System.DateTime CreateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ABS_Contract> ABS_Contract { get; set; }
        public virtual MasterData MasterData { get; set; }
        public virtual MDG_Dictionary MDG_Dictionary { get; set; }
        public virtual SYS_Organization SYS_Organization { get; set; }
        public virtual SYS_User SYS_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MDG_Employee> MDG_Employee1 { get; set; }
        public virtual MDG_Employee MDG_Employee2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MDR_ET> MDR_ET { get; set; }
    }
}
