//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight.WS.Server.Common.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class MDG_Contact
    {
        public System.Guid MID { get; set; }
        public long SN { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public Nullable<int> Gender { get; set; }
        public string Department { get; set; }
        public string Title { get; set; }
        public string OfficeAddress { get; set; }
        public string HomeAddress { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Description { get; set; }
        public bool IsMaster { get; set; }
        public bool Enable { get; set; }
        public bool LoginUser { get; set; }
        public Nullable<System.Guid> CreatorDeptId { get; set; }
        public System.Guid CreatorUserId { get; set; }
        public System.DateTime CreateTime { get; set; }
    
        public virtual MasterData MasterData { get; set; }
        public virtual SYS_Organization SYS_Organization { get; set; }
        public virtual SYS_User SYS_User { get; set; }
    }
}
