//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight.WS.Server.Common.ORM
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    
    public partial class OrderList
    {
    	[DataMember]
        public System.Guid ID { get; set; }
    	[DataMember]
        public System.Guid MemberId { get; set; }
    	[DataMember]
        public System.Guid SubjectId { get; set; }
    	[DataMember]
        public string ProductName { get; set; }
    	[DataMember]
        public string ProductSpeci { get; set; }
    	[DataMember]
        public decimal ProductPrice { get; set; }
    	[DataMember]
        public decimal OrderAmount { get; set; }
    	[DataMember]
        public decimal FirstPay { get; set; }
    	[DataMember]
        public string ProductImage { get; set; }
    	[DataMember]
        public Nullable<System.Guid> StagePlan { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> OutDate { get; set; }
    	[DataMember]
        public System.DateTime CreateTime { get; set; }
    	[DataMember]
        public string Status { get; set; }
    	[DataMember]
        public decimal Interest { get; set; }
    }
}
