//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight.WS.Server.Common.ORM
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(MasterData))]
    [KnownType(typeof(SDC_FirstVisit))]
    [KnownType(typeof(SYS_User))]
    
    public partial class SDC_Subsequent
    {
    	[DataMember]
        public System.Guid ID { get; set; }
    	[DataMember]
        public long SN { get; set; }
    	[DataMember]
        public Nullable<System.Guid> CaseId { get; set; }
    	[DataMember]
        public string MedicalHistory { get; set; }
    	[DataMember]
        public string Inspection { get; set; }
    	[DataMember]
        public string TherapyPlan { get; set; }
    	[DataMember]
        public string Therapy { get; set; }
    	[DataMember]
        public string Notify { get; set; }
    	[DataMember]
        public string KeyWord { get; set; }
    	[DataMember]
        public string Description { get; set; }
    	[DataMember]
        public Nullable<System.Guid> DoctorId { get; set; }
    	[DataMember]
        public Nullable<System.Guid> NurseId { get; set; }
    	[DataMember]
        public System.Guid CreatorUserId { get; set; }
    	[DataMember]
        public System.DateTime CreateTime { get; set; }
    
    	[DataMember]
        public virtual MasterData MasterData { get; set; }
    	[DataMember]
        public virtual MasterData MasterData1 { get; set; }
    	[DataMember]
        public virtual SDC_FirstVisit SDC_FirstVisit { get; set; }
    	[DataMember]
        public virtual SYS_User SYS_User { get; set; }
    }
}
