//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight.WS.Server.Common.ORM
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(SYS_User))]
    [KnownType(typeof(SDT_Voice))]
    [KnownType(typeof(SDT_Praise))]
    
    public partial class SDT_Comment
    {
        public SDT_Comment()
        {
            this.SDT_Praise = new HashSet<SDT_Praise>();
        }
    
    	[DataMember]
        public System.Guid ID { get; set; }
    	[DataMember]
        public long SN { get; set; }
    	[DataMember]
        public System.Guid VoiceId { get; set; }
    	[DataMember]
        public string Content { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> PublishTime { get; set; }
    	[DataMember]
        public System.Guid CreatorUserId { get; set; }
    	[DataMember]
        public System.DateTime CreateTime { get; set; }
    
    	[DataMember]
        public virtual SYS_User SYS_User { get; set; }
    	[DataMember]
        public virtual SDT_Voice SDT_Voice { get; set; }
    	[DataMember]
        public virtual ICollection<SDT_Praise> SDT_Praise { get; set; }
    }
}
