//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight.WS.Server.Common.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_Verify_Record
    {
        public System.Guid ID { get; set; }
        public long SN { get; set; }
        public int Type { get; set; }
        public string Mobile { get; set; }
        public string Code { get; set; }
        public bool Verified { get; set; }
        public Nullable<System.DateTime> VerifyTime { get; set; }
        public Nullable<System.DateTime> FailureTime { get; set; }
        public System.DateTime CreateTime { get; set; }
    }
}
