//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight.WS.Server.Common.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_Report_Definition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SYS_Report_Definition()
        {
            this.SYS_Report_Period = new HashSet<SYS_Report_Period>();
            this.SYS_Report_Entity = new HashSet<SYS_Report_Entity>();
            this.SYS_Report_Schedular = new HashSet<SYS_Report_Schedular>();
            this.SYS_Report_Instances = new HashSet<SYS_Report_Instances>();
        }
    
        public System.Guid ID { get; set; }
        public long SN { get; set; }
        public System.Guid CategoryId { get; set; }
        public string Name { get; set; }
        public System.Guid TemplateId { get; set; }
        public int Mode { get; set; }
        public int Delay { get; set; }
        public int Type { get; set; }
        public string DataSource { get; set; }
        public string Description { get; set; }
        public Nullable<System.Guid> CreatorDeptId { get; set; }
        public System.Guid CreatorUserId { get; set; }
        public System.DateTime CreateTime { get; set; }
    
        public virtual BASE_Category BASE_Category { get; set; }
        public virtual SYS_Organization SYS_Organization { get; set; }
        public virtual SYS_User SYS_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYS_Report_Period> SYS_Report_Period { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYS_Report_Entity> SYS_Report_Entity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYS_Report_Schedular> SYS_Report_Schedular { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SYS_Report_Instances> SYS_Report_Instances { get; set; }
        public virtual SYS_Report_Templates SYS_Report_Templates { get; set; }
    }
}
