//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight.WS.Server.Common.ORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYS_Interface
    {
        public System.Guid ID { get; set; }
        public long SN { get; set; }
        public string Binding { get; set; }
        public string Name { get; set; }
        public string Class { get; set; }
        public string Interface { get; set; }
        public string Location { get; set; }
    }
}
