//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight.WS.Server.Common.ORM
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    
    public partial class Topics
    {
    	[DataMember]
        public System.Guid ID { get; set; }
    	[DataMember]
        public Nullable<System.Guid> GroupId { get; set; }
    	[DataMember]
        public System.Guid TopicId { get; set; }
    	[DataMember]
        public bool Private { get; set; }
    	[DataMember]
        public string Title { get; set; }
    	[DataMember]
        public Nullable<System.Guid> SpeechId { get; set; }
    	[DataMember]
        public string Content { get; set; }
    	[DataMember]
        public Nullable<System.Guid> MemberId { get; set; }
    	[DataMember]
        public string Portrait { get; set; }
    	[DataMember]
        public Nullable<int> Agrees { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> PublishTime { get; set; }
    }
}
