//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight.WS.Server.Common.ORM
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(ABS_Contract_Subjects))]
    [KnownType(typeof(ImageData))]
    [KnownType(typeof(MasterData))]
    [KnownType(typeof(MDG_Customer))]
    [KnownType(typeof(MDG_Supplier))]
    
    public partial class BASE_Category
    {
        public BASE_Category()
        {
            this.ABS_Contract_Subjects = new HashSet<ABS_Contract_Subjects>();
            this.ImageData = new HashSet<ImageData>();
            this.MasterData = new HashSet<MasterData>();
            this.MDG_Customer = new HashSet<MDG_Customer>();
            this.MDG_Customer1 = new HashSet<MDG_Customer>();
            this.MDG_Supplier = new HashSet<MDG_Supplier>();
            this.MDG_Supplier1 = new HashSet<MDG_Supplier>();
        }
    
    	[DataMember]
        public System.Guid ID { get; set; }
    	[DataMember]
        public long SN { get; set; }
    	[DataMember]
        public Nullable<System.Guid> ParentId { get; set; }
    	[DataMember]
        public System.Guid ModuleId { get; set; }
    	[DataMember]
        public int Index { get; set; }
    	[DataMember]
        public string Code { get; set; }
    	[DataMember]
        public string Name { get; set; }
    	[DataMember]
        public string Alias { get; set; }
    	[DataMember]
        public string Description { get; set; }
    	[DataMember]
        public bool BuiltIn { get; set; }
    	[DataMember]
        public bool Visible { get; set; }
    	[DataMember]
        public Nullable<System.Guid> CreatorDeptId { get; set; }
    	[DataMember]
        public System.Guid CreatorUserId { get; set; }
    	[DataMember]
        public System.DateTime CreateTime { get; set; }
    
    	[DataMember]
        public virtual ICollection<ABS_Contract_Subjects> ABS_Contract_Subjects { get; set; }
    	[DataMember]
        public virtual ICollection<ImageData> ImageData { get; set; }
    	[DataMember]
        public virtual ICollection<MasterData> MasterData { get; set; }
    	[DataMember]
        public virtual ICollection<MDG_Customer> MDG_Customer { get; set; }
    	[DataMember]
        public virtual ICollection<MDG_Customer> MDG_Customer1 { get; set; }
    	[DataMember]
        public virtual ICollection<MDG_Supplier> MDG_Supplier { get; set; }
    	[DataMember]
        public virtual ICollection<MDG_Supplier> MDG_Supplier1 { get; set; }
    }
}
