//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight.WS.Server.Common.ORM
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(ABS_Advance))]
    [KnownType(typeof(ABS_Advance_Detail))]
    [KnownType(typeof(ABS_Clearing))]
    [KnownType(typeof(ABS_Clearing_Item))]
    [KnownType(typeof(ABS_Contract))]
    [KnownType(typeof(ABS_Contract_Subjects))]
    [KnownType(typeof(ABS_Delivery))]
    [KnownType(typeof(ABS_Delivery_Item))]
    [KnownType(typeof(ABS_Storage_Summary))]
    [KnownType(typeof(BASE_Category))]
    [KnownType(typeof(MDG_Contact))]
    [KnownType(typeof(MDG_Customer))]
    [KnownType(typeof(MDG_Dictionary))]
    [KnownType(typeof(MDG_Employee))]
    [KnownType(typeof(MDG_Expense))]
    [KnownType(typeof(MDG_Material))]
    [KnownType(typeof(MDG_Supplier))]
    [KnownType(typeof(MDR_MU))]
    [KnownType(typeof(MDS_Contact_Info))]
    [KnownType(typeof(SYS_Alert_Target))]
    [KnownType(typeof(SYS_Alert_Send))]
    [KnownType(typeof(MDE_Message))]
    [KnownType(typeof(MDG_Member))]
    [KnownType(typeof(SDC_FirstVisit))]
    [KnownType(typeof(SDC_Subsequent))]
    [KnownType(typeof(SDG_GroupMember))]
    
    public partial class MasterData
    {
        public MasterData()
        {
            this.ABS_Advance = new HashSet<ABS_Advance>();
            this.ABS_Advance_Detail = new HashSet<ABS_Advance_Detail>();
            this.ABS_Clearing = new HashSet<ABS_Clearing>();
            this.ABS_Clearing_Item = new HashSet<ABS_Clearing_Item>();
            this.ABS_Contract = new HashSet<ABS_Contract>();
            this.ABS_Contract1 = new HashSet<ABS_Contract>();
            this.ABS_Contract_Subjects = new HashSet<ABS_Contract_Subjects>();
            this.ABS_Delivery = new HashSet<ABS_Delivery>();
            this.ABS_Delivery_Item = new HashSet<ABS_Delivery_Item>();
            this.ABS_Storage_Summary = new HashSet<ABS_Storage_Summary>();
            this.MDR_MU = new HashSet<MDR_MU>();
            this.MDS_Contact_Info = new HashSet<MDS_Contact_Info>();
            this.SYS_Alert_Target = new HashSet<SYS_Alert_Target>();
            this.SYS_Alert_Send = new HashSet<SYS_Alert_Send>();
            this.MDE_Message = new HashSet<MDE_Message>();
            this.SDC_FirstVisit = new HashSet<SDC_FirstVisit>();
            this.SDC_FirstVisit1 = new HashSet<SDC_FirstVisit>();
            this.SDC_Subsequent = new HashSet<SDC_Subsequent>();
            this.SDC_Subsequent1 = new HashSet<SDC_Subsequent>();
            this.SDG_GroupMember = new HashSet<SDG_GroupMember>();
        }
    
    	[DataMember]
        public System.Guid ID { get; set; }
    	[DataMember]
        public long SN { get; set; }
    	[DataMember]
        public Nullable<System.Guid> ParentId { get; set; }
    	[DataMember]
        public Nullable<System.Guid> CategoryId { get; set; }
    	[DataMember]
        public string Code { get; set; }
    	[DataMember]
        public string Name { get; set; }
    	[DataMember]
        public string Alias { get; set; }
    	[DataMember]
        public string FullName { get; set; }
    
    	[DataMember]
        public virtual ICollection<ABS_Advance> ABS_Advance { get; set; }
    	[DataMember]
        public virtual ICollection<ABS_Advance_Detail> ABS_Advance_Detail { get; set; }
    	[DataMember]
        public virtual ICollection<ABS_Clearing> ABS_Clearing { get; set; }
    	[DataMember]
        public virtual ICollection<ABS_Clearing_Item> ABS_Clearing_Item { get; set; }
    	[DataMember]
        public virtual ICollection<ABS_Contract> ABS_Contract { get; set; }
    	[DataMember]
        public virtual ICollection<ABS_Contract> ABS_Contract1 { get; set; }
    	[DataMember]
        public virtual ICollection<ABS_Contract_Subjects> ABS_Contract_Subjects { get; set; }
    	[DataMember]
        public virtual ICollection<ABS_Delivery> ABS_Delivery { get; set; }
    	[DataMember]
        public virtual ICollection<ABS_Delivery_Item> ABS_Delivery_Item { get; set; }
    	[DataMember]
        public virtual ICollection<ABS_Storage_Summary> ABS_Storage_Summary { get; set; }
    	[DataMember]
        public virtual BASE_Category BASE_Category { get; set; }
    	[DataMember]
        public virtual MDG_Contact MDG_Contact { get; set; }
    	[DataMember]
        public virtual MDG_Customer MDG_Customer { get; set; }
    	[DataMember]
        public virtual MDG_Dictionary MDG_Dictionary { get; set; }
    	[DataMember]
        public virtual MDG_Employee MDG_Employee { get; set; }
    	[DataMember]
        public virtual MDG_Expense MDG_Expense { get; set; }
    	[DataMember]
        public virtual MDG_Material MDG_Material { get; set; }
    	[DataMember]
        public virtual MDG_Supplier MDG_Supplier { get; set; }
    	[DataMember]
        public virtual ICollection<MDR_MU> MDR_MU { get; set; }
    	[DataMember]
        public virtual ICollection<MDS_Contact_Info> MDS_Contact_Info { get; set; }
    	[DataMember]
        public virtual ICollection<SYS_Alert_Target> SYS_Alert_Target { get; set; }
    	[DataMember]
        public virtual ICollection<SYS_Alert_Send> SYS_Alert_Send { get; set; }
    	[DataMember]
        public virtual ICollection<MDE_Message> MDE_Message { get; set; }
    	[DataMember]
        public virtual MDG_Member MDG_Member { get; set; }
    	[DataMember]
        public virtual ICollection<SDC_FirstVisit> SDC_FirstVisit { get; set; }
    	[DataMember]
        public virtual ICollection<SDC_FirstVisit> SDC_FirstVisit1 { get; set; }
    	[DataMember]
        public virtual ICollection<SDC_Subsequent> SDC_Subsequent { get; set; }
    	[DataMember]
        public virtual ICollection<SDC_Subsequent> SDC_Subsequent1 { get; set; }
    	[DataMember]
        public virtual ICollection<SDG_GroupMember> SDG_GroupMember { get; set; }
    }
}
