//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight.WS.Server.Common.ORM
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(ABS_Advance))]
    [KnownType(typeof(ABS_Clearing_Pay))]
    [KnownType(typeof(ABS_Contract_FundPlan))]
    [KnownType(typeof(ABS_StockDetail))]
    [KnownType(typeof(ABS_Storage_Location))]
    [KnownType(typeof(ABS_Storage_Summary))]
    [KnownType(typeof(ImageData))]
    [KnownType(typeof(MasterData))]
    [KnownType(typeof(MDG_Customer))]
    [KnownType(typeof(MDG_Employee))]
    [KnownType(typeof(MDG_Expense))]
    [KnownType(typeof(MDG_Material))]
    [KnownType(typeof(MDG_Supplier))]
    [KnownType(typeof(MDS_Contact_Info))]
    
    public partial class MDG_Dictionary
    {
        public MDG_Dictionary()
        {
            this.ABS_Advance = new HashSet<ABS_Advance>();
            this.ABS_Clearing_Pay = new HashSet<ABS_Clearing_Pay>();
            this.ABS_Clearing_Pay1 = new HashSet<ABS_Clearing_Pay>();
            this.ABS_Contract_FundPlan = new HashSet<ABS_Contract_FundPlan>();
            this.ABS_StockDetail = new HashSet<ABS_StockDetail>();
            this.ABS_Storage_Location = new HashSet<ABS_Storage_Location>();
            this.ABS_Storage_Summary = new HashSet<ABS_Storage_Summary>();
            this.ImageData = new HashSet<ImageData>();
            this.MDG_Customer = new HashSet<MDG_Customer>();
            this.MDG_Customer1 = new HashSet<MDG_Customer>();
            this.MDG_Customer2 = new HashSet<MDG_Customer>();
            this.MDG_Customer3 = new HashSet<MDG_Customer>();
            this.MDG_Customer4 = new HashSet<MDG_Customer>();
            this.MDG_Customer5 = new HashSet<MDG_Customer>();
            this.MDG_Employee = new HashSet<MDG_Employee>();
            this.MDG_Expense = new HashSet<MDG_Expense>();
            this.MDG_Material = new HashSet<MDG_Material>();
            this.MDG_Material1 = new HashSet<MDG_Material>();
            this.MDG_Material2 = new HashSet<MDG_Material>();
            this.MDG_Supplier = new HashSet<MDG_Supplier>();
            this.MDG_Supplier1 = new HashSet<MDG_Supplier>();
            this.MDG_Supplier2 = new HashSet<MDG_Supplier>();
            this.MDG_Supplier3 = new HashSet<MDG_Supplier>();
            this.MDS_Contact_Info = new HashSet<MDS_Contact_Info>();
        }
    
    	[DataMember]
        public System.Guid MID { get; set; }
    	[DataMember]
        public long SN { get; set; }
    	[DataMember]
        public int Index { get; set; }
    	[DataMember]
        public string Type { get; set; }
    	[DataMember]
        public string Description { get; set; }
    	[DataMember]
        public bool BuiltIn { get; set; }
    	[DataMember]
        public bool Enable { get; set; }
    	[DataMember]
        public Nullable<System.Guid> CreatorDeptId { get; set; }
    	[DataMember]
        public System.Guid CreatorUserId { get; set; }
    	[DataMember]
        public System.DateTime CreateTime { get; set; }
    
    	[DataMember]
        public virtual ICollection<ABS_Advance> ABS_Advance { get; set; }
    	[DataMember]
        public virtual ICollection<ABS_Clearing_Pay> ABS_Clearing_Pay { get; set; }
    	[DataMember]
        public virtual ICollection<ABS_Clearing_Pay> ABS_Clearing_Pay1 { get; set; }
    	[DataMember]
        public virtual ICollection<ABS_Contract_FundPlan> ABS_Contract_FundPlan { get; set; }
    	[DataMember]
        public virtual ICollection<ABS_StockDetail> ABS_StockDetail { get; set; }
    	[DataMember]
        public virtual ICollection<ABS_Storage_Location> ABS_Storage_Location { get; set; }
    	[DataMember]
        public virtual ICollection<ABS_Storage_Summary> ABS_Storage_Summary { get; set; }
    	[DataMember]
        public virtual ICollection<ImageData> ImageData { get; set; }
    	[DataMember]
        public virtual MasterData MasterData { get; set; }
    	[DataMember]
        public virtual ICollection<MDG_Customer> MDG_Customer { get; set; }
    	[DataMember]
        public virtual ICollection<MDG_Customer> MDG_Customer1 { get; set; }
    	[DataMember]
        public virtual ICollection<MDG_Customer> MDG_Customer2 { get; set; }
    	[DataMember]
        public virtual ICollection<MDG_Customer> MDG_Customer3 { get; set; }
    	[DataMember]
        public virtual ICollection<MDG_Customer> MDG_Customer4 { get; set; }
    	[DataMember]
        public virtual ICollection<MDG_Customer> MDG_Customer5 { get; set; }
    	[DataMember]
        public virtual ICollection<MDG_Employee> MDG_Employee { get; set; }
    	[DataMember]
        public virtual ICollection<MDG_Expense> MDG_Expense { get; set; }
    	[DataMember]
        public virtual ICollection<MDG_Material> MDG_Material { get; set; }
    	[DataMember]
        public virtual ICollection<MDG_Material> MDG_Material1 { get; set; }
    	[DataMember]
        public virtual ICollection<MDG_Material> MDG_Material2 { get; set; }
    	[DataMember]
        public virtual ICollection<MDG_Supplier> MDG_Supplier { get; set; }
    	[DataMember]
        public virtual ICollection<MDG_Supplier> MDG_Supplier1 { get; set; }
    	[DataMember]
        public virtual ICollection<MDG_Supplier> MDG_Supplier2 { get; set; }
    	[DataMember]
        public virtual ICollection<MDG_Supplier> MDG_Supplier3 { get; set; }
    	[DataMember]
        public virtual ICollection<MDS_Contact_Info> MDS_Contact_Info { get; set; }
    }
}
