//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight.WS.Server.Common.ORM
{
    using System;
    using System.Runtime.Serialization;
    
    public partial class Topics
    {
        public Nullable<System.Guid> ID { get; set; }
        public Nullable<bool> Private { get; set; }
        public string Title { get; set; }
        public Nullable<System.Guid> SpeechId { get; set; }
        public string Content { get; set; }
        public Nullable<System.Guid> MemberId { get; set; }
        public string Portrait { get; set; }
        public Nullable<int> Agrees { get; set; }
        public Nullable<System.DateTime> PublishTime { get; set; }
    }
}
