//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight.WS.Test
{
    using System;
    
    public partial class SYS_Logs
    {
        public Guid ID { get; set; }

        public long SN { get; set; }

        public Level Level { get; set; }

        public string Code { get; set; }

        public string Source { get; set; }

        public string Action { get; set; }

        public string Message { get; set; }

        public Guid? SourceUserId { get; set; }

        public DateTime CreateTime { get; set; }
    }

    /// <summary>
    /// 日志等级
    /// </summary>
    public enum Level
    {
        Emergency,
        Alert,
        Critical,
        Error,
        Warning,
        Notice,
        Informational,
        Debug
    }
}
