//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Insight.WS.Server.Common
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(ABS_Clearing))]
    [KnownType(typeof(SYS_Organization))]
    [KnownType(typeof(SYS_User))]
    [KnownType(typeof(ImageData))]
    
    public partial class ABS_Clearing_Check
    {
        public ABS_Clearing_Check()
        {
            this.ABS_Clearing = new HashSet<ABS_Clearing>();
        }
    
    	[DataMember]
        public Guid ID { get; set; }
    	[DataMember]
        public long SN { get; set; }
    	[DataMember]
        public string ReceiptCode { get; set; }
    	[DataMember]
        public Nullable<DateTime> CheckTime { get; set; }
    	[DataMember]
        public Nullable<Guid> ImageId { get; set; }
    	[DataMember]
        public bool Status { get; set; }
    	[DataMember]
        public string Description { get; set; }
    	[DataMember]
        public Guid CreatorDeptId { get; set; }
    	[DataMember]
        public Guid CreatorUserId { get; set; }
    	[DataMember]
        public DateTime CreateTime { get; set; }
    
    	[DataMember]
        public virtual ICollection<ABS_Clearing> ABS_Clearing { get; set; }
    	[DataMember]
        public virtual SYS_Organization SYS_Organization { get; set; }
    	[DataMember]
        public virtual SYS_User SYS_User { get; set; }
    	[DataMember]
        public virtual ImageData ImageData { get; set; }
    }
}
