//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Insight.WS.Server.Common
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(ABS_Contract_FundPerform))]
    [KnownType(typeof(MDG_Dictionary))]
    [KnownType(typeof(ABS_Contract_Subjects))]
    [KnownType(typeof(ABS_Contract))]
    
    public partial class ABS_Contract_FundPlan
    {
        public ABS_Contract_FundPlan()
        {
            this.ABS_Contract_FundPerform = new HashSet<ABS_Contract_FundPerform>();
        }
    
    	[DataMember]
        public Guid ID { get; set; }
    	[DataMember]
        public long SN { get; set; }
    	[DataMember]
        public Nullable<Guid> SubjectsId { get; set; }
    	[DataMember]
        public Nullable<Guid> ParentId { get; set; }
    	[DataMember]
        public Nullable<Guid> CurrencyId { get; set; }
    	[DataMember]
        public decimal Amount { get; set; }
    	[DataMember]
        public DateTime StartDate { get; set; }
    	[DataMember]
        public DateTime EndDate { get; set; }
    	[DataMember]
        public Nullable<DateTime> Ex_StartDate { get; set; }
    	[DataMember]
        public Nullable<DateTime> Ex_EndDate { get; set; }
    	[DataMember]
        public string Description { get; set; }
    	[DataMember]
        public DateTime CreateTime { get; set; }
    	[DataMember]
        public Guid ContractId { get; set; }
    
    	[DataMember]
        public virtual ICollection<ABS_Contract_FundPerform> ABS_Contract_FundPerform { get; set; }
    	[DataMember]
        public virtual MDG_Dictionary MDG_Dictionary { get; set; }
    	[DataMember]
        public virtual ABS_Contract_Subjects ABS_Contract_Subjects { get; set; }
    	[DataMember]
        public virtual ABS_Contract ABS_Contract { get; set; }
    }
}
