//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Insight.WS.Server.Common
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(MasterData))]
    [KnownType(typeof(ABS_Advance))]
    [KnownType(typeof(ABS_Advance_Record))]
    
    public partial class ABS_Advance_Detail
    {
        public ABS_Advance_Detail()
        {
            this.ABS_Advance_Record = new HashSet<ABS_Advance_Record>();
        }
    
    	[DataMember]
        public Guid ID { get; set; }
    	[DataMember]
        public long SN { get; set; }
    	[DataMember]
        public Guid AccountId { get; set; }
    	[DataMember]
        public Nullable<Guid> ObjectId { get; set; }
    	[DataMember]
        public int Type { get; set; }
    	[DataMember]
        public decimal Amount { get; set; }
    	[DataMember]
        public Nullable<DateTime> ValidDate { get; set; }
    
    	[DataMember]
        public virtual MasterData MasterData { get; set; }
    	[DataMember]
        public virtual ABS_Advance ABS_Advance { get; set; }
    	[DataMember]
        public virtual ICollection<ABS_Advance_Record> ABS_Advance_Record { get; set; }
    }
}
