//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Insight.WS.Server.Common
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(ABS_Advance_Detail))]
    [KnownType(typeof(MDG_Dictionary))]
    [KnownType(typeof(SYS_Organization))]
    [KnownType(typeof(SYS_User))]
    [KnownType(typeof(MasterData))]
    
    public partial class ABS_Advance
    {
        public ABS_Advance()
        {
            this.ABS_Advance_Detail = new HashSet<ABS_Advance_Detail>();
        }
    
    	[DataMember]
        public Guid ID { get; set; }
    	[DataMember]
        public long SN { get; set; }
    	[DataMember]
        public string AccountNo { get; set; }
    	[DataMember]
        public Nullable<Guid> CardType { get; set; }
    	[DataMember]
        public Guid OwnerId { get; set; }
    	[DataMember]
        public int Status { get; set; }
    	[DataMember]
        public string Description { get; set; }
    	[DataMember]
        public Guid CreatorDeptId { get; set; }
    	[DataMember]
        public Guid CreatorUserId { get; set; }
    	[DataMember]
        public DateTime CreateTime { get; set; }
    
    	[DataMember]
        public virtual ICollection<ABS_Advance_Detail> ABS_Advance_Detail { get; set; }
    	[DataMember]
        public virtual MDG_Dictionary MDG_Dictionary { get; set; }
    	[DataMember]
        public virtual SYS_Organization SYS_Organization { get; set; }
    	[DataMember]
        public virtual SYS_User SYS_User { get; set; }
    	[DataMember]
        public virtual MasterData MasterData { get; set; }
    }
}
