//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Insight.WS.Server.Common
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(ABS_Storage_Detail))]
    [KnownType(typeof(MDG_Dictionary))]
    [KnownType(typeof(MasterData))]
    
    public partial class ABS_Storage_Summary
    {
        public ABS_Storage_Summary()
        {
            this.ABS_Storage_Detail = new HashSet<ABS_Storage_Detail>();
        }
    
    	[DataMember]
        public Guid ID { get; set; }
    	[DataMember]
        public long SN { get; set; }
    	[DataMember]
        public Nullable<Guid> GoodsType { get; set; }
    	[DataMember]
        public Guid SKUId { get; set; }
    	[DataMember]
        public Nullable<decimal> Total { get; set; }
    
    	[DataMember]
        public virtual ICollection<ABS_Storage_Detail> ABS_Storage_Detail { get; set; }
    	[DataMember]
        public virtual MDG_Dictionary MDG_Dictionary { get; set; }
    	[DataMember]
        public virtual MasterData MasterData { get; set; }
    }
}
