//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Runtime.Serialization;

namespace Insight.WS.Server.Common
{
    [DataContract(IsReference = true)]
    
    public partial class Advance
    {
    	[DataMember]
        public Guid ID { get; set; }
    	[DataMember]
        public Guid OwnerId { get; set; }
    	[DataMember]
        public string AccountNo { get; set; }
    	[DataMember]
        public Nullable<Guid> CardType { get; set; }
    	[DataMember]
        public Nullable<int> Pri { get; set; }
    	[DataMember]
        public Nullable<Guid> ObjectId { get; set; }
    	[DataMember]
        public int Type { get; set; }
    	[DataMember]
        public Nullable<DateTime> ValidDate { get; set; }
    	[DataMember]
        public decimal Amount { get; set; }
    }
}
