//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Runtime.Serialization;

namespace Insight.WS.Server.Common
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(MDG_Dictionary))]
    [KnownType(typeof(ABS_Contract_Subjects))]
    
    public partial class BIZ_Reimburse_Detail
    {
    	[DataMember]
        public Guid SID { get; set; }
    	[DataMember]
        public long SN { get; set; }
    	[DataMember]
        public Nullable<Guid> ExpensesType { get; set; }
    
    	[DataMember]
        public virtual MDG_Dictionary MDG_Dictionary { get; set; }
    	[DataMember]
        public virtual ABS_Contract_Subjects ABS_Contract_Subjects { get; set; }
    }
}
