//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Runtime.Serialization;

namespace Insight.WS.Server.Common
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(MasterData))]
    [KnownType(typeof(SYS_Alert_Message))]
    
    public partial class SYS_Alert_Send
    {
    	[DataMember]
        public Guid ID { get; set; }
    	[DataMember]
        public long SN { get; set; }
    	[DataMember]
        public Guid MessageId { get; set; }
    	[DataMember]
        public Nullable<Guid> TargetId { get; set; }
    	[DataMember]
        public Nullable<int> SendType { get; set; }
    	[DataMember]
        public string Target { get; set; }
    	[DataMember]
        public Nullable<int> Times { get; set; }
    	[DataMember]
        public Nullable<DateTime> SendTime { get; set; }
    	[DataMember]
        public int Status { get; set; }
    
    	[DataMember]
        public virtual MasterData MasterData { get; set; }
    	[DataMember]
        public virtual SYS_Alert_Message SYS_Alert_Message { get; set; }
    }
}
