//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Insight.WS.Server.Common
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(SYS_Organization))]
    [KnownType(typeof(SYS_Report_Definition))]
    [KnownType(typeof(SYS_Report_Member))]
    
    public partial class SYS_Report_Entity
    {
        public SYS_Report_Entity()
        {
            this.SYS_Report_Member = new HashSet<SYS_Report_Member>();
        }
    
    	[DataMember]
        public Guid ID { get; set; }
    	[DataMember]
        public long SN { get; set; }
    	[DataMember]
        public Guid ReportId { get; set; }
    	[DataMember]
        public Guid OrgId { get; set; }
    
    	[DataMember]
        public virtual SYS_Organization SYS_Organization { get; set; }
    	[DataMember]
        public virtual SYS_Report_Definition SYS_Report_Definition { get; set; }
    	[DataMember]
        public virtual ICollection<SYS_Report_Member> SYS_Report_Member { get; set; }
    }
}
