//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Runtime.Serialization;

namespace Insight.WS.Server.Common
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(SYS_Code_Scheme))]
    
    public partial class SYS_Code_Record
    {
    	[DataMember]
        public Guid ID { get; set; }
    	[DataMember]
        public long SN { get; set; }
    	[DataMember]
        public Guid SchemeId { get; set; }
    	[DataMember]
        public string RelationChar { get; set; }
    	[DataMember]
        public int SerialNumber { get; set; }
    	[DataMember]
        public Nullable<Guid> BusinessId { get; set; }
    	[DataMember]
        public DateTime CreateTime { get; set; }
    
    	[DataMember]
        public virtual SYS_Code_Scheme SYS_Code_Scheme { get; set; }
    }
}
