//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Runtime.Serialization;

namespace Insight.WS.Server.Common
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(SYS_Report_Instances))]
    [KnownType(typeof(SYS_User))]
    
    public partial class SYS_Report_IU
    {
    	[DataMember]
        public Guid ID { get; set; }
    	[DataMember]
        public long SN { get; set; }
    	[DataMember]
        public Guid InstanceId { get; set; }
    	[DataMember]
        public Guid UserId { get; set; }
    
    	[DataMember]
        public virtual SYS_Report_Instances SYS_Report_Instances { get; set; }
    	[DataMember]
        public virtual SYS_User SYS_User { get; set; }
    }
}
