//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Runtime.Serialization;

namespace Insight.WS.Server.Common
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(SYS_Module))]
    [KnownType(typeof(SYS_Organization))]
    [KnownType(typeof(SYS_User))]
    
    public partial class SYS_ModuleParam
    {
    	[DataMember]
        public Guid ID { get; set; }
    	[DataMember]
        public long SN { get; set; }
    	[DataMember]
        public Guid ModuleId { get; set; }
    	[DataMember]
        public Guid ParamId { get; set; }
    	[DataMember]
        public string Name { get; set; }
    	[DataMember]
        public string Value { get; set; }
    	[DataMember]
        public Nullable<Guid> OrgId { get; set; }
    	[DataMember]
        public Nullable<Guid> UserId { get; set; }
    	[DataMember]
        public string Description { get; set; }
    
    	[DataMember]
        public virtual SYS_Module SYS_Module { get; set; }
    	[DataMember]
        public virtual SYS_Organization SYS_Organization { get; set; }
    	[DataMember]
        public virtual SYS_User SYS_User { get; set; }
    }
}
