//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SERP.Server.Common
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    [DataContract(IsReference = true)]
    public partial class TitleMember
    {
        [DataMember]
        public System.Guid ID { get; set; }
        [DataMember]
        public string 用户名 { get; set; }
        [DataMember]
        public string 登录名 { get; set; }
        [DataMember]
        public string 状态 { get; set; }
        [DataMember]
        public System.Guid TitleId { get; set; }
    }
}
