//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight.WS.Server.Common.YUN
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    
    public partial class Orders
    {
    	[DataMember]
        public int Orders_ID { get; set; }
    	[DataMember]
        public string Orders_SN { get; set; }
    	[DataMember]
        public Nullable<int> Orders_BuyerID { get; set; }
    	[DataMember]
        public Nullable<int> Orders_SysUserID { get; set; }
    	[DataMember]
        public Nullable<int> Orders_Status { get; set; }
    	[DataMember]
        public Nullable<int> Orders_ERPSyncStatus { get; set; }
    	[DataMember]
        public Nullable<int> Orders_PaymentStatus { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> Orders_PaymentStatus_Time { get; set; }
    	[DataMember]
        public Nullable<int> Orders_DeliveryStatus { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> Orders_DeliveryStatus_Time { get; set; }
    	[DataMember]
        public Nullable<int> Orders_InvoiceStatus { get; set; }
    	[DataMember]
        public Nullable<int> Orders_Fail_SysUserID { get; set; }
    	[DataMember]
        public string Orders_Fail_Note { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> Orders_Fail_Addtime { get; set; }
    	[DataMember]
        public Nullable<int> Orders_IsReturnCoin { get; set; }
    	[DataMember]
        public Nullable<decimal> Orders_Total_MKTPrice { get; set; }
    	[DataMember]
        public Nullable<decimal> Orders_Total_Price { get; set; }
    	[DataMember]
        public Nullable<decimal> Orders_Total_Freight { get; set; }
    	[DataMember]
        public Nullable<int> Orders_Total_Coin { get; set; }
    	[DataMember]
        public Nullable<int> Orders_Total_UseCoin { get; set; }
    	[DataMember]
        public Nullable<decimal> Orders_Total_PriceDiscount { get; set; }
    	[DataMember]
        public Nullable<decimal> Orders_Total_FreightDiscount { get; set; }
    	[DataMember]
        public string Orders_Total_PriceDiscount_Note { get; set; }
    	[DataMember]
        public string Orders_Total_FreightDiscount_Note { get; set; }
    	[DataMember]
        public Nullable<decimal> Orders_Total_AllPrice { get; set; }
    	[DataMember]
        public Nullable<int> Orders_Address_ID { get; set; }
    	[DataMember]
        public string Orders_Address_Country { get; set; }
    	[DataMember]
        public string Orders_Address_State { get; set; }
    	[DataMember]
        public string Orders_Address_City { get; set; }
    	[DataMember]
        public string Orders_Address_County { get; set; }
    	[DataMember]
        public string Orders_Address_StreetAddress { get; set; }
    	[DataMember]
        public string Orders_Address_Zip { get; set; }
    	[DataMember]
        public string Orders_Address_Name { get; set; }
    	[DataMember]
        public string Orders_Address_Phone_Countrycode { get; set; }
    	[DataMember]
        public string Orders_Address_Phone_Areacode { get; set; }
    	[DataMember]
        public string Orders_Address_Phone_Number { get; set; }
    	[DataMember]
        public string Orders_Address_Mobile { get; set; }
    	[DataMember]
        public Nullable<int> Orders_Delivery_Time_ID { get; set; }
    	[DataMember]
        public Nullable<int> Orders_Delivery { get; set; }
    	[DataMember]
        public string Orders_Delivery_Name { get; set; }
    	[DataMember]
        public Nullable<int> Orders_Payway { get; set; }
    	[DataMember]
        public string Orders_Payway_Name { get; set; }
    	[DataMember]
        public string Orders_Note { get; set; }
    	[DataMember]
        public string Orders_Admin_Note { get; set; }
    	[DataMember]
        public Nullable<int> Orders_Admin_Sign { get; set; }
    	[DataMember]
        public string Orders_Site { get; set; }
    	[DataMember]
        public Nullable<int> Orders_SourceType { get; set; }
    	[DataMember]
        public string Orders_Source { get; set; }
    	[DataMember]
        public string Orders_VerifyCode { get; set; }
    	[DataMember]
        public Nullable<int> U_Orders_IsMonitor { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> Orders_Addtime { get; set; }
    	[DataMember]
        public string Orders_From { get; set; }
    	[DataMember]
        public Nullable<decimal> Orders_Account_Pay { get; set; }
    	[DataMember]
        public Nullable<decimal> Orders_Card_Pay { get; set; }
    	[DataMember]
        public Nullable<decimal> Orders_Total_RemainPrice { get; set; }
    	[DataMember]
        public Nullable<decimal> Orders_Settle_Price { get; set; }
    	[DataMember]
        public Nullable<int> Orders_IsEvaluate { get; set; }
    	[DataMember]
        public Nullable<int> U_Orders_SMS_Status { get; set; }
    	[DataMember]
        public Nullable<int> U_Orders_IsPush { get; set; }
    	[DataMember]
        public Nullable<int> Orders_SupplierID { get; set; }
    	[DataMember]
        public string Orders_BankOrderSN { get; set; }
    	[DataMember]
        public Nullable<int> Orders_TieIn_Status { get; set; }
    	[DataMember]
        public Nullable<decimal> Orders_Settle_Account { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> Orders_Settle_Date { get; set; }
    	[DataMember]
        public string Orders_Settle_Note { get; set; }
    	[DataMember]
        public Nullable<int> Orders_Settle_IsSettle { get; set; }
    	[DataMember]
        public Nullable<int> Orders_BankAuditPass { get; set; }
    	[DataMember]
        public Nullable<int> Orders_IsUrgency { get; set; }
    	[DataMember]
        public Nullable<int> Orders_ShipmentsType { get; set; }
    	[DataMember]
        public Nullable<int> Orders_ApplyStatus { get; set; }
    	[DataMember]
        public string Orders_Delivery_Requirements { get; set; }
    	[DataMember]
        public Nullable<int> Orders_PriorityLevel { get; set; }
    	[DataMember]
        public Nullable<int> Orders_PriorityCoefficient { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> Orders_PriorityLevelTime { get; set; }
    	[DataMember]
        public string Orders_Credit_Card_No { get; set; }
    	[DataMember]
        public string Orders_ID_No { get; set; }
    	[DataMember]
        public string Orders_Installment { get; set; }
    	[DataMember]
        public Nullable<double> Orders_Point { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> Orders_Delivery_Time { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> Orders_Cancel_Time { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> Orders_Return_Time { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> Order_Confirm_Time { get; set; }
    	[DataMember]
        public Nullable<int> Orders_RefundStatus { get; set; }
    	[DataMember]
        public string Orders_TieIn_SN { get; set; }
    	[DataMember]
        public Nullable<int> Orders_KFConfirmSMS { get; set; }
    	[DataMember]
        public string Orders_Import_Type { get; set; }
    	[DataMember]
        public string Orders_Import_Cardholder { get; set; }
    	[DataMember]
        public string Orders_Import_cardholder_Tel { get; set; }
    	[DataMember]
        public string Orders_Import_MainOrdersID { get; set; }
    	[DataMember]
        public string Orders_OldGoods { get; set; }
    }
}
