//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight.WS.Server.Common.YUN
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    
    public partial class Orders_Delivery
    {
    	[DataMember]
        public int Orders_Delivery_ID { get; set; }
    	[DataMember]
        public Nullable<int> Orders_Delivery_OrdersID { get; set; }
    	[DataMember]
        public Nullable<int> Orders_Delivery_DeliveryStatus { get; set; }
    	[DataMember]
        public Nullable<int> Orders_Delivery_SysUserID { get; set; }
    	[DataMember]
        public string Orders_Delivery_DocNo { get; set; }
    	[DataMember]
        public string Orders_Delivery_Name { get; set; }
    	[DataMember]
        public string Orders_Delivery_companyName { get; set; }
    	[DataMember]
        public string Orders_Delivery_Code { get; set; }
    	[DataMember]
        public Nullable<decimal> Orders_Delivery_Amount { get; set; }
    	[DataMember]
        public string Orders_Delivery_Note { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> Orders_Delivery_Addtime { get; set; }
    	[DataMember]
        public string Orders_Delivery_Site { get; set; }
    	[DataMember]
        public Nullable<int> Orders_Delivery_SupplierID { get; set; }
    	[DataMember]
        public string Orders_Delivery_BankSN { get; set; }
    }
}
