//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight.WS.Server.Common.YUN
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    
    public partial class Orders_Payment
    {
    	[DataMember]
        public int Orders_Payment_ID { get; set; }
    	[DataMember]
        public Nullable<int> Orders_Payment_OrdersID { get; set; }
    	[DataMember]
        public Nullable<int> Orders_Payment_PaymentStatus { get; set; }
    	[DataMember]
        public Nullable<int> Orders_Payment_SysUserID { get; set; }
    	[DataMember]
        public string Orders_Payment_DocNo { get; set; }
    	[DataMember]
        public string Orders_Payment_Name { get; set; }
    	[DataMember]
        public Nullable<decimal> Orders_Payment_Amount { get; set; }
    	[DataMember]
        public string Orders_Payment_Note { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> Orders_Payment_Addtime { get; set; }
    	[DataMember]
        public string Orders_Payment_Site { get; set; }
    }
}
