//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight.WS.Server.Common.YUN
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    
    public partial class Orders_Settle
    {
    	[DataMember]
        public int Settle_ID { get; set; }
    	[DataMember]
        public string Settle_Source { get; set; }
    	[DataMember]
        public string Settle_OrdersSN { get; set; }
    	[DataMember]
        public Nullable<int> Settle_OrdersID { get; set; }
    	[DataMember]
        public Nullable<decimal> Settle_Price { get; set; }
    	[DataMember]
        public string Settile_ReturnData { get; set; }
    	[DataMember]
        public string Settile_Note { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> Settile_AddTime { get; set; }
    }
}
