//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight.WS.Server.Common.YUN
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    
    public partial class ProductType_Brand
    {
    	[DataMember]
        public int ProductType_Brand_ID { get; set; }
    	[DataMember]
        public Nullable<int> ProductType_Brand_ProductTypeID { get; set; }
    	[DataMember]
        public Nullable<int> ProductType_Brand_BrandID { get; set; }
    }
}
