//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight.WS.Server.Common.YUN
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    
    public partial class Products
    {
    	[DataMember]
        public int ID { get; set; }
    	[DataMember]
        public string GroupCode { get; set; }
    	[DataMember]
        public string Code { get; set; }
    	[DataMember]
        public string Category { get; set; }
    	[DataMember]
        public Nullable<int> TypeId { get; set; }
    	[DataMember]
        public string Name { get; set; }
    	[DataMember]
        public string Color { get; set; }
    	[DataMember]
        public Nullable<decimal> MarketPrice { get; set; }
    	[DataMember]
        public decimal SalePrice { get; set; }
    	[DataMember]
        public int OutDay { get; set; }
    	[DataMember]
        public string ImageUrl { get; set; }
    	[DataMember]
        public string Description { get; set; }
    	[DataMember]
        public string Parameter { get; set; }
    	[DataMember]
        public string Warranty { get; set; }
    	[DataMember]
        public bool Recommend { get; set; }
    	[DataMember]
        public string Product_Site { get; set; }
    	[DataMember]
        public bool Insale { get; set; }
    }
}
