//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight.WS.Client.Platform.Base.Service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Service.IBase")]
    internal interface IBase {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBase/GetOnlineUser", ReplyAction="http://tempuri.org/IBase/GetOnlineUserResponse")]
        System.Collections.Generic.List<Insight.WS.Client.Common.Service.Session> GetOnlineUser(Insight.WS.Client.Common.Service.Session us);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBase/GetOrgs", ReplyAction="http://tempuri.org/IBase/GetOrgsResponse")]
        System.Data.DataTable GetOrgs(Insight.WS.Client.Common.Service.Session us);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBase/GetOrg", ReplyAction="http://tempuri.org/IBase/GetOrgResponse")]
        Insight.WS.Client.Common.Service.SYS_Organization GetOrg(Insight.WS.Client.Common.Service.Session us, System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBase/GetOrgMembers", ReplyAction="http://tempuri.org/IBase/GetOrgMembersResponse")]
        System.Data.DataTable GetOrgMembers(Insight.WS.Client.Common.Service.Session us);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBase/GetOrgMemberBeSides", ReplyAction="http://tempuri.org/IBase/GetOrgMemberBeSidesResponse")]
        System.Data.DataTable GetOrgMemberBeSides(Insight.WS.Client.Common.Service.Session us, System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBase/AddOrg", ReplyAction="http://tempuri.org/IBase/AddOrgResponse")]
        bool AddOrg(Insight.WS.Client.Common.Service.Session us, Insight.WS.Client.Common.Service.SYS_Organization obj, int index);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBase/AddOrgMerger", ReplyAction="http://tempuri.org/IBase/AddOrgMergerResponse")]
        bool AddOrgMerger(Insight.WS.Client.Common.Service.Session us, Insight.WS.Client.Common.Service.SYS_OrgMerger obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBase/AddOrgMember", ReplyAction="http://tempuri.org/IBase/AddOrgMemberResponse")]
        bool AddOrgMember(Insight.WS.Client.Common.Service.Session us, System.Guid oid, System.Collections.Generic.List<System.Guid> uids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBase/UpdateOrg", ReplyAction="http://tempuri.org/IBase/UpdateOrgResponse")]
        bool UpdateOrg(Insight.WS.Client.Common.Service.Session us, Insight.WS.Client.Common.Service.SYS_Organization obj, int index);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBase/UpdateOrgParentId", ReplyAction="http://tempuri.org/IBase/UpdateOrgParentIdResponse")]
        bool UpdateOrgParentId(Insight.WS.Client.Common.Service.Session us, Insight.WS.Client.Common.Service.SYS_Organization obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBase/DeleteOrg", ReplyAction="http://tempuri.org/IBase/DeleteOrgResponse")]
        bool DeleteOrg(Insight.WS.Client.Common.Service.Session us, System.Guid oid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBase/DeleteOrgMember", ReplyAction="http://tempuri.org/IBase/DeleteOrgMemberResponse")]
        bool DeleteOrgMember(Insight.WS.Client.Common.Service.Session us, System.Collections.Generic.List<System.Guid> ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBase/GetGroups", ReplyAction="http://tempuri.org/IBase/GetGroupsResponse")]
        System.Data.DataTable GetGroups(Insight.WS.Client.Common.Service.Session us);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBase/GetGroup", ReplyAction="http://tempuri.org/IBase/GetGroupResponse")]
        Insight.WS.Client.Common.Service.SYS_UserGroup GetGroup(Insight.WS.Client.Common.Service.Session us, System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBase/GetUsers", ReplyAction="http://tempuri.org/IBase/GetUsersResponse")]
        System.Data.DataTable GetUsers(Insight.WS.Client.Common.Service.Session us);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBase/GetUser", ReplyAction="http://tempuri.org/IBase/GetUserResponse")]
        Insight.WS.Client.Common.Service.SYS_User GetUser(Insight.WS.Client.Common.Service.Session us, System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBase/GetGroupMembers", ReplyAction="http://tempuri.org/IBase/GetGroupMembersResponse")]
        System.Data.DataTable GetGroupMembers(Insight.WS.Client.Common.Service.Session us);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBase/GetGroupMemberBeSides", ReplyAction="http://tempuri.org/IBase/GetGroupMemberBeSidesResponse")]
        System.Data.DataTable GetGroupMemberBeSides(Insight.WS.Client.Common.Service.Session us, System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBase/AddGroup", ReplyAction="http://tempuri.org/IBase/AddGroupResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.Session))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.LoginResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.Session>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_Organization))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.ABS_Advance>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.ABS_Advance))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.ABS_Advance_Detail>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.ABS_Advance_Detail))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.ABS_Advance_Record>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.ABS_Advance_Record))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.ABS_Clearing))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.ABS_Clearing_Attachs>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.ABS_Clearing_Attachs))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.ImageData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.ABS_Clearing_Check>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.ABS_Clearing_Check))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.ABS_Clearing>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_User))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.ABS_Contract>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.ABS_Contract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.ABS_Contract_Attachs>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.ABS_Contract_Attachs))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.MDG_Material))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.MDG_Dictionary))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.ABS_Clearing_Pay>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.ABS_Clearing_Pay))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.ABS_Clearing_Item))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.ABS_Contract_FundPerform>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.ABS_Contract_FundPerform))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.ABS_Contract_FundPlan))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.ABS_Contract_Subjects))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.ABS_Contract_FundPlan>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.ABS_Contract_GoodsPlan>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.ABS_Contract_GoodsPlan))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.ABS_Contract_GoodsPerform>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.ABS_Contract_GoodsPerform))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.ABS_Delivery_Item))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.ABS_Delivery))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.ABS_Delivery_Attachs>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.ABS_Delivery_Attachs))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_Code_Scheme))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_Allot_Record>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_Allot_Record))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_Module))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.BASE_Category>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.BASE_Category))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.ABS_Contract_Subjects>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.ImageData>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.MDG_Customer>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.MDG_Customer))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.MasterData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.ABS_Clearing_Item>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.ABS_Delivery>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.ABS_Delivery_Item>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.ABS_Storage_Summary>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.ABS_Storage_Summary))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.ABS_Storage_Detail>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.ABS_Storage_Detail))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.ABS_Storage_Location))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.MDG_Supplier))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.BIZ_Travel_Apply))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.BIZ_Travel_Plan>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.BIZ_Travel_Plan))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.MDD_Numeric))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.MasterData_Property))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.MDD_Binary>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.MDD_Binary))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.MDD_Character))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_Code_Allot))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_Code_Record))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_OrgMerger))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.MDD_Date))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_RolePerm_DataAbs))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_Role))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_Report_Member>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_Report_Member))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_Report_Entity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_Report_Definition))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_Report_Entity>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_Report_Instances>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_Report_Instances))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_Report_IU>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_Report_IU))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.MDG_Employee))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.MDG_Employee>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.MDR_ET>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.MDR_ET))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_Role_Title))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.BIZ_Refund_Apply))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.BIZ_Reimburse_Detail))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.MasterData_Merger))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_RolePerm_Action))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_ModuleAction))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_RolePerm_Action>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.BIZ_Refund_Detail))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.ABS_StockDetail))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.ABS_StockCapital))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.ABS_StockDetail>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.BIZ_Borrowing_Apply))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_RolePerm_Data))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.MDG_Expense))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_Role_User))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.MDS_Contact_Info))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.MDG_Contact))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_Role_UserGroup))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_UserGroup))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_Role_UserGroup>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_UserGroupMember>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_UserGroupMember))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.BIZ_Reimburse_Apply))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_Report_Templates))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_Report_Definition>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.MDR_MU))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_Report_Period))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_Report_Rules))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_Report_Period>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_Report_Schedular>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_Report_Schedular))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_Alert_Target))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_Alert_Rules))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_Alert_Message>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_Alert_Message))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_Alert_Send>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_Alert_Send))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_ModuleGroup))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_Module>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_OrgMember))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_ModuleParam))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_Alert_Target>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_RolePerm_Data>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_RolePerm_DataAbs>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_Role_Title>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_Role_User>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.MDD_Character>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.MDD_Date>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.MDD_Numeric>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.MDR_MU>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.MDS_Contact_Info>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.MasterData_Merger>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.MDG_Supplier>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.MasterData>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.MasterData_Property>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_Alert_Rules>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_Report_Templates>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_Code_Allot>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_ModuleAction>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_ModuleParam>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_Code_Record>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.BIZ_Refund_Detail>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.ABS_Storage_Location>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.BIZ_Borrowing_Apply>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.BIZ_Refund_Apply>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.BIZ_Reimburse_Detail>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.BIZ_Travel_Apply>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.MDG_Expense>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.MDG_Material>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_Organization>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.MDG_Contact>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.MDG_Dictionary>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_Code_Scheme>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_OrgMember>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_OrgMerger>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_Report_Rules>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_Role>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_UserGroup>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.ABS_StockCapital>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<System.Guid>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<object>))]
        object AddGroup(Insight.WS.Client.Common.Service.Session us, Insight.WS.Client.Common.Service.SYS_UserGroup obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBase/AddUser", ReplyAction="http://tempuri.org/IBase/AddUserResponse")]
        bool AddUser(Insight.WS.Client.Common.Service.Session us, Insight.WS.Client.Common.Service.SYS_User obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBase/AddGroupMember", ReplyAction="http://tempuri.org/IBase/AddGroupMemberResponse")]
        bool AddGroupMember(Insight.WS.Client.Common.Service.Session us, System.Guid gid, System.Collections.Generic.List<System.Guid> uids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBase/UpdateGroup", ReplyAction="http://tempuri.org/IBase/UpdateGroupResponse")]
        bool UpdateGroup(Insight.WS.Client.Common.Service.Session us, Insight.WS.Client.Common.Service.SYS_UserGroup obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBase/UpdateUser", ReplyAction="http://tempuri.org/IBase/UpdateUserResponse")]
        bool UpdateUser(Insight.WS.Client.Common.Service.Session us, Insight.WS.Client.Common.Service.SYS_User obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBase/UpdateUserStatus", ReplyAction="http://tempuri.org/IBase/UpdateUserStatusResponse")]
        bool UpdateUserStatus(Insight.WS.Client.Common.Service.Session us, System.Guid id, bool validity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBase/DeleteGroup", ReplyAction="http://tempuri.org/IBase/DeleteGroupResponse")]
        bool DeleteGroup(Insight.WS.Client.Common.Service.Session us, System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBase/DeleteUser", ReplyAction="http://tempuri.org/IBase/DeleteUserResponse")]
        bool DeleteUser(Insight.WS.Client.Common.Service.Session us, System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBase/DeleteMember", ReplyAction="http://tempuri.org/IBase/DeleteMemberResponse")]
        bool DeleteMember(Insight.WS.Client.Common.Service.Session us, System.Collections.Generic.List<System.Guid> ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBase/GetAllRole", ReplyAction="http://tempuri.org/IBase/GetAllRoleResponse")]
        System.Data.DataTable GetAllRole(Insight.WS.Client.Common.Service.Session us);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBase/GetRole", ReplyAction="http://tempuri.org/IBase/GetRoleResponse")]
        Insight.WS.Client.Common.Service.SYS_Role GetRole(Insight.WS.Client.Common.Service.Session us, System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBase/GetRoleMember", ReplyAction="http://tempuri.org/IBase/GetRoleMemberResponse")]
        System.Data.DataTable GetRoleMember(Insight.WS.Client.Common.Service.Session us);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBase/GetRoleUser", ReplyAction="http://tempuri.org/IBase/GetRoleUserResponse")]
        System.Data.DataTable GetRoleUser(Insight.WS.Client.Common.Service.Session us);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBase/GetRoleModulePermit", ReplyAction="http://tempuri.org/IBase/GetRoleModulePermitResponse")]
        System.Data.DataTable GetRoleModulePermit(Insight.WS.Client.Common.Service.Session us);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBase/GetRoleActionPermit", ReplyAction="http://tempuri.org/IBase/GetRoleActionPermitResponse")]
        System.Data.DataTable GetRoleActionPermit(Insight.WS.Client.Common.Service.Session us);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBase/GetRoleDataPermit", ReplyAction="http://tempuri.org/IBase/GetRoleDataPermitResponse")]
        System.Data.DataTable GetRoleDataPermit(Insight.WS.Client.Common.Service.Session us);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBase/GetMemberOfTitle", ReplyAction="http://tempuri.org/IBase/GetMemberOfTitleResponse")]
        System.Data.DataTable GetMemberOfTitle(Insight.WS.Client.Common.Service.Session us, System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBase/GetMemberOfGroup", ReplyAction="http://tempuri.org/IBase/GetMemberOfGroupResponse")]
        System.Data.DataTable GetMemberOfGroup(Insight.WS.Client.Common.Service.Session us, System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBase/GetMemberOfUser", ReplyAction="http://tempuri.org/IBase/GetMemberOfUserResponse")]
        System.Data.DataTable GetMemberOfUser(Insight.WS.Client.Common.Service.Session us, System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBase/GetRoleActions", ReplyAction="http://tempuri.org/IBase/GetRoleActionsResponse")]
        System.Data.DataTable GetRoleActions(Insight.WS.Client.Common.Service.Session us, System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBase/GetRoleRelData", ReplyAction="http://tempuri.org/IBase/GetRoleRelDataResponse")]
        System.Data.DataTable GetRoleRelData(Insight.WS.Client.Common.Service.Session us, System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBase/AddRole", ReplyAction="http://tempuri.org/IBase/AddRoleResponse")]
        bool AddRole(Insight.WS.Client.Common.Service.Session us, Insight.WS.Client.Common.Service.SYS_Role obj, System.Data.DataTable action, System.Data.DataTable data, System.Data.DataTable custom);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBase/AddRoleMember", ReplyAction="http://tempuri.org/IBase/AddRoleMemberResponse")]
        bool AddRoleMember(Insight.WS.Client.Common.Service.Session us, System.Guid id, System.Collections.Generic.List<System.Guid> tids, System.Collections.Generic.List<System.Guid> gids, System.Collections.Generic.List<System.Guid> uids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBase/EditRole", ReplyAction="http://tempuri.org/IBase/EditRoleResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.Session))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.LoginResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.Session>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_Organization))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.ABS_Advance>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.ABS_Advance))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.ABS_Advance_Detail>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.ABS_Advance_Detail))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.ABS_Advance_Record>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.ABS_Advance_Record))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.ABS_Clearing))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.ABS_Clearing_Attachs>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.ABS_Clearing_Attachs))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.ImageData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.ABS_Clearing_Check>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.ABS_Clearing_Check))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.ABS_Clearing>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_User))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.ABS_Contract>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.ABS_Contract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.ABS_Contract_Attachs>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.ABS_Contract_Attachs))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.MDG_Material))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.MDG_Dictionary))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.ABS_Clearing_Pay>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.ABS_Clearing_Pay))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.ABS_Clearing_Item))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.ABS_Contract_FundPerform>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.ABS_Contract_FundPerform))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.ABS_Contract_FundPlan))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.ABS_Contract_Subjects))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.ABS_Contract_FundPlan>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.ABS_Contract_GoodsPlan>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.ABS_Contract_GoodsPlan))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.ABS_Contract_GoodsPerform>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.ABS_Contract_GoodsPerform))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.ABS_Delivery_Item))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.ABS_Delivery))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.ABS_Delivery_Attachs>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.ABS_Delivery_Attachs))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_Code_Scheme))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_Allot_Record>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_Allot_Record))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_Module))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.BASE_Category>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.BASE_Category))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.ABS_Contract_Subjects>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.ImageData>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.MDG_Customer>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.MDG_Customer))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.MasterData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.ABS_Clearing_Item>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.ABS_Delivery>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.ABS_Delivery_Item>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.ABS_Storage_Summary>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.ABS_Storage_Summary))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.ABS_Storage_Detail>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.ABS_Storage_Detail))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.ABS_Storage_Location))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.MDG_Supplier))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.BIZ_Travel_Apply))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.BIZ_Travel_Plan>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.BIZ_Travel_Plan))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.MDD_Numeric))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.MasterData_Property))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.MDD_Binary>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.MDD_Binary))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.MDD_Character))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_Code_Allot))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_Code_Record))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_OrgMerger))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.MDD_Date))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_RolePerm_DataAbs))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_Role))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_Report_Member>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_Report_Member))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_Report_Entity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_Report_Definition))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_Report_Entity>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_Report_Instances>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_Report_Instances))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_Report_IU>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_Report_IU))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.MDG_Employee))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.MDG_Employee>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.MDR_ET>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.MDR_ET))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_Role_Title))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.BIZ_Refund_Apply))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.BIZ_Reimburse_Detail))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.MasterData_Merger))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_RolePerm_Action))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_ModuleAction))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_RolePerm_Action>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.BIZ_Refund_Detail))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.ABS_StockDetail))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.ABS_StockCapital))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.ABS_StockDetail>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.BIZ_Borrowing_Apply))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_RolePerm_Data))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.MDG_Expense))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_Role_User))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.MDS_Contact_Info))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.MDG_Contact))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_Role_UserGroup))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_UserGroup))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_Role_UserGroup>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_UserGroupMember>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_UserGroupMember))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.BIZ_Reimburse_Apply))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_Report_Templates))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_Report_Definition>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.MDR_MU))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_Report_Period))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_Report_Rules))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_Report_Period>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_Report_Schedular>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_Report_Schedular))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_Alert_Target))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_Alert_Rules))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_Alert_Message>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_Alert_Message))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_Alert_Send>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_Alert_Send))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_ModuleGroup))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_Module>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_OrgMember))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_ModuleParam))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_Alert_Target>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_RolePerm_Data>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_RolePerm_DataAbs>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_Role_Title>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_Role_User>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.MDD_Character>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.MDD_Date>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.MDD_Numeric>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.MDR_MU>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.MDS_Contact_Info>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.MasterData_Merger>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.MDG_Supplier>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.MasterData>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.MasterData_Property>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_Alert_Rules>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_Report_Templates>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_Code_Allot>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_ModuleAction>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_ModuleParam>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_Code_Record>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.BIZ_Refund_Detail>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.ABS_Storage_Location>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.BIZ_Borrowing_Apply>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.BIZ_Refund_Apply>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.BIZ_Reimburse_Detail>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.BIZ_Travel_Apply>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.MDG_Expense>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.MDG_Material>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_Organization>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.MDG_Contact>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.MDG_Dictionary>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_Code_Scheme>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_OrgMember>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_OrgMerger>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_Report_Rules>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_Role>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_UserGroup>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.ABS_StockCapital>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<System.Guid>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<object>))]
        bool EditRole(Insight.WS.Client.Common.Service.Session us, Insight.WS.Client.Common.Service.SYS_Role obj, System.Collections.Generic.List<object> adl, System.Collections.Generic.List<object> ddl, System.Collections.Generic.List<object> cdl, System.Data.DataTable adt, System.Data.DataTable ddt, System.Data.DataTable cdt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBase/DeleteRole", ReplyAction="http://tempuri.org/IBase/DeleteRoleResponse")]
        bool DeleteRole(Insight.WS.Client.Common.Service.Session us, System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBase/DeleteRoleMember", ReplyAction="http://tempuri.org/IBase/DeleteRoleMemberResponse")]
        bool DeleteRoleMember(Insight.WS.Client.Common.Service.Session us, int type, System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBase/GetSchemes", ReplyAction="http://tempuri.org/IBase/GetSchemesResponse")]
        System.Data.DataTable GetSchemes(Insight.WS.Client.Common.Service.Session us);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBase/GetSerialRecord", ReplyAction="http://tempuri.org/IBase/GetSerialRecordResponse")]
        System.Data.DataTable GetSerialRecord(Insight.WS.Client.Common.Service.Session us);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBase/GetAllotRecord", ReplyAction="http://tempuri.org/IBase/GetAllotRecordResponse")]
        System.Data.DataTable GetAllotRecord(Insight.WS.Client.Common.Service.Session us);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBase/GetScheme", ReplyAction="http://tempuri.org/IBase/GetSchemeResponse")]
        Insight.WS.Client.Common.Service.SYS_Code_Scheme GetScheme(Insight.WS.Client.Common.Service.Session us, System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBase/GetCodePreview", ReplyAction="http://tempuri.org/IBase/GetCodePreviewResponse")]
        string GetCodePreview(Insight.WS.Client.Common.Service.Session us, System.Guid sid, string code, string mark);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBase/AddScheme", ReplyAction="http://tempuri.org/IBase/AddSchemeResponse")]
        bool AddScheme(Insight.WS.Client.Common.Service.Session us, Insight.WS.Client.Common.Service.SYS_Code_Scheme obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBase/UpdateScheme", ReplyAction="http://tempuri.org/IBase/UpdateSchemeResponse")]
        bool UpdateScheme(Insight.WS.Client.Common.Service.Session us, Insight.WS.Client.Common.Service.SYS_Code_Scheme obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBase/EnableScheme", ReplyAction="http://tempuri.org/IBase/EnableSchemeResponse")]
        bool EnableScheme(Insight.WS.Client.Common.Service.Session us, System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBase/DeleteScheme", ReplyAction="http://tempuri.org/IBase/DeleteSchemeResponse")]
        int DeleteScheme(Insight.WS.Client.Common.Service.Session us, System.Guid id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface IBaseChannel : Insight.WS.Client.Platform.Base.Service.IBase, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class BaseClient : System.ServiceModel.ClientBase<Insight.WS.Client.Platform.Base.Service.IBase>, Insight.WS.Client.Platform.Base.Service.IBase {
        
        public BaseClient() {
        }
        
        public BaseClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BaseClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BaseClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BaseClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<Insight.WS.Client.Common.Service.Session> GetOnlineUser(Insight.WS.Client.Common.Service.Session us) {
            return base.Channel.GetOnlineUser(us);
        }
        
        public System.Data.DataTable GetOrgs(Insight.WS.Client.Common.Service.Session us) {
            return base.Channel.GetOrgs(us);
        }
        
        public Insight.WS.Client.Common.Service.SYS_Organization GetOrg(Insight.WS.Client.Common.Service.Session us, System.Guid id) {
            return base.Channel.GetOrg(us, id);
        }
        
        public System.Data.DataTable GetOrgMembers(Insight.WS.Client.Common.Service.Session us) {
            return base.Channel.GetOrgMembers(us);
        }
        
        public System.Data.DataTable GetOrgMemberBeSides(Insight.WS.Client.Common.Service.Session us, System.Guid id) {
            return base.Channel.GetOrgMemberBeSides(us, id);
        }
        
        public bool AddOrg(Insight.WS.Client.Common.Service.Session us, Insight.WS.Client.Common.Service.SYS_Organization obj, int index) {
            return base.Channel.AddOrg(us, obj, index);
        }
        
        public bool AddOrgMerger(Insight.WS.Client.Common.Service.Session us, Insight.WS.Client.Common.Service.SYS_OrgMerger obj) {
            return base.Channel.AddOrgMerger(us, obj);
        }
        
        public bool AddOrgMember(Insight.WS.Client.Common.Service.Session us, System.Guid oid, System.Collections.Generic.List<System.Guid> uids) {
            return base.Channel.AddOrgMember(us, oid, uids);
        }
        
        public bool UpdateOrg(Insight.WS.Client.Common.Service.Session us, Insight.WS.Client.Common.Service.SYS_Organization obj, int index) {
            return base.Channel.UpdateOrg(us, obj, index);
        }
        
        public bool UpdateOrgParentId(Insight.WS.Client.Common.Service.Session us, Insight.WS.Client.Common.Service.SYS_Organization obj) {
            return base.Channel.UpdateOrgParentId(us, obj);
        }
        
        public bool DeleteOrg(Insight.WS.Client.Common.Service.Session us, System.Guid oid) {
            return base.Channel.DeleteOrg(us, oid);
        }
        
        public bool DeleteOrgMember(Insight.WS.Client.Common.Service.Session us, System.Collections.Generic.List<System.Guid> ids) {
            return base.Channel.DeleteOrgMember(us, ids);
        }
        
        public System.Data.DataTable GetGroups(Insight.WS.Client.Common.Service.Session us) {
            return base.Channel.GetGroups(us);
        }
        
        public Insight.WS.Client.Common.Service.SYS_UserGroup GetGroup(Insight.WS.Client.Common.Service.Session us, System.Guid id) {
            return base.Channel.GetGroup(us, id);
        }
        
        public System.Data.DataTable GetUsers(Insight.WS.Client.Common.Service.Session us) {
            return base.Channel.GetUsers(us);
        }
        
        public Insight.WS.Client.Common.Service.SYS_User GetUser(Insight.WS.Client.Common.Service.Session us, System.Guid id) {
            return base.Channel.GetUser(us, id);
        }
        
        public System.Data.DataTable GetGroupMembers(Insight.WS.Client.Common.Service.Session us) {
            return base.Channel.GetGroupMembers(us);
        }
        
        public System.Data.DataTable GetGroupMemberBeSides(Insight.WS.Client.Common.Service.Session us, System.Guid id) {
            return base.Channel.GetGroupMemberBeSides(us, id);
        }
        
        public object AddGroup(Insight.WS.Client.Common.Service.Session us, Insight.WS.Client.Common.Service.SYS_UserGroup obj) {
            return base.Channel.AddGroup(us, obj);
        }
        
        public bool AddUser(Insight.WS.Client.Common.Service.Session us, Insight.WS.Client.Common.Service.SYS_User obj) {
            return base.Channel.AddUser(us, obj);
        }
        
        public bool AddGroupMember(Insight.WS.Client.Common.Service.Session us, System.Guid gid, System.Collections.Generic.List<System.Guid> uids) {
            return base.Channel.AddGroupMember(us, gid, uids);
        }
        
        public bool UpdateGroup(Insight.WS.Client.Common.Service.Session us, Insight.WS.Client.Common.Service.SYS_UserGroup obj) {
            return base.Channel.UpdateGroup(us, obj);
        }
        
        public bool UpdateUser(Insight.WS.Client.Common.Service.Session us, Insight.WS.Client.Common.Service.SYS_User obj) {
            return base.Channel.UpdateUser(us, obj);
        }
        
        public bool UpdateUserStatus(Insight.WS.Client.Common.Service.Session us, System.Guid id, bool validity) {
            return base.Channel.UpdateUserStatus(us, id, validity);
        }
        
        public bool DeleteGroup(Insight.WS.Client.Common.Service.Session us, System.Guid id) {
            return base.Channel.DeleteGroup(us, id);
        }
        
        public bool DeleteUser(Insight.WS.Client.Common.Service.Session us, System.Guid id) {
            return base.Channel.DeleteUser(us, id);
        }
        
        public bool DeleteMember(Insight.WS.Client.Common.Service.Session us, System.Collections.Generic.List<System.Guid> ids) {
            return base.Channel.DeleteMember(us, ids);
        }
        
        public System.Data.DataTable GetAllRole(Insight.WS.Client.Common.Service.Session us) {
            return base.Channel.GetAllRole(us);
        }
        
        public Insight.WS.Client.Common.Service.SYS_Role GetRole(Insight.WS.Client.Common.Service.Session us, System.Guid id) {
            return base.Channel.GetRole(us, id);
        }
        
        public System.Data.DataTable GetRoleMember(Insight.WS.Client.Common.Service.Session us) {
            return base.Channel.GetRoleMember(us);
        }
        
        public System.Data.DataTable GetRoleUser(Insight.WS.Client.Common.Service.Session us) {
            return base.Channel.GetRoleUser(us);
        }
        
        public System.Data.DataTable GetRoleModulePermit(Insight.WS.Client.Common.Service.Session us) {
            return base.Channel.GetRoleModulePermit(us);
        }
        
        public System.Data.DataTable GetRoleActionPermit(Insight.WS.Client.Common.Service.Session us) {
            return base.Channel.GetRoleActionPermit(us);
        }
        
        public System.Data.DataTable GetRoleDataPermit(Insight.WS.Client.Common.Service.Session us) {
            return base.Channel.GetRoleDataPermit(us);
        }
        
        public System.Data.DataTable GetMemberOfTitle(Insight.WS.Client.Common.Service.Session us, System.Guid id) {
            return base.Channel.GetMemberOfTitle(us, id);
        }
        
        public System.Data.DataTable GetMemberOfGroup(Insight.WS.Client.Common.Service.Session us, System.Guid id) {
            return base.Channel.GetMemberOfGroup(us, id);
        }
        
        public System.Data.DataTable GetMemberOfUser(Insight.WS.Client.Common.Service.Session us, System.Guid id) {
            return base.Channel.GetMemberOfUser(us, id);
        }
        
        public System.Data.DataTable GetRoleActions(Insight.WS.Client.Common.Service.Session us, System.Guid id) {
            return base.Channel.GetRoleActions(us, id);
        }
        
        public System.Data.DataTable GetRoleRelData(Insight.WS.Client.Common.Service.Session us, System.Guid id) {
            return base.Channel.GetRoleRelData(us, id);
        }
        
        public bool AddRole(Insight.WS.Client.Common.Service.Session us, Insight.WS.Client.Common.Service.SYS_Role obj, System.Data.DataTable action, System.Data.DataTable data, System.Data.DataTable custom) {
            return base.Channel.AddRole(us, obj, action, data, custom);
        }
        
        public bool AddRoleMember(Insight.WS.Client.Common.Service.Session us, System.Guid id, System.Collections.Generic.List<System.Guid> tids, System.Collections.Generic.List<System.Guid> gids, System.Collections.Generic.List<System.Guid> uids) {
            return base.Channel.AddRoleMember(us, id, tids, gids, uids);
        }
        
        public bool EditRole(Insight.WS.Client.Common.Service.Session us, Insight.WS.Client.Common.Service.SYS_Role obj, System.Collections.Generic.List<object> adl, System.Collections.Generic.List<object> ddl, System.Collections.Generic.List<object> cdl, System.Data.DataTable adt, System.Data.DataTable ddt, System.Data.DataTable cdt) {
            return base.Channel.EditRole(us, obj, adl, ddl, cdl, adt, ddt, cdt);
        }
        
        public bool DeleteRole(Insight.WS.Client.Common.Service.Session us, System.Guid id) {
            return base.Channel.DeleteRole(us, id);
        }
        
        public bool DeleteRoleMember(Insight.WS.Client.Common.Service.Session us, int type, System.Guid id) {
            return base.Channel.DeleteRoleMember(us, type, id);
        }
        
        public System.Data.DataTable GetSchemes(Insight.WS.Client.Common.Service.Session us) {
            return base.Channel.GetSchemes(us);
        }
        
        public System.Data.DataTable GetSerialRecord(Insight.WS.Client.Common.Service.Session us) {
            return base.Channel.GetSerialRecord(us);
        }
        
        public System.Data.DataTable GetAllotRecord(Insight.WS.Client.Common.Service.Session us) {
            return base.Channel.GetAllotRecord(us);
        }
        
        public Insight.WS.Client.Common.Service.SYS_Code_Scheme GetScheme(Insight.WS.Client.Common.Service.Session us, System.Guid id) {
            return base.Channel.GetScheme(us, id);
        }
        
        public string GetCodePreview(Insight.WS.Client.Common.Service.Session us, System.Guid sid, string code, string mark) {
            return base.Channel.GetCodePreview(us, sid, code, mark);
        }
        
        public bool AddScheme(Insight.WS.Client.Common.Service.Session us, Insight.WS.Client.Common.Service.SYS_Code_Scheme obj) {
            return base.Channel.AddScheme(us, obj);
        }
        
        public bool UpdateScheme(Insight.WS.Client.Common.Service.Session us, Insight.WS.Client.Common.Service.SYS_Code_Scheme obj) {
            return base.Channel.UpdateScheme(us, obj);
        }
        
        public bool EnableScheme(Insight.WS.Client.Common.Service.Session us, System.Guid id) {
            return base.Channel.EnableScheme(us, id);
        }
        
        public int DeleteScheme(Insight.WS.Client.Common.Service.Session us, System.Guid id) {
            return base.Channel.DeleteScheme(us, id);
        }
    }
}
