//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using System.Data;
using System.Diagnostics;
using System.ServiceModel;
using System.ServiceModel.Channels;
using Insight.WS.Client.Common.Service;

namespace Insight.WS.Client.Business.SCM.Service {
    
    
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    [ServiceContract(ConfigurationName="Service.ISCM")]
    internal interface ISCM {
        
        [OperationContract(Action="http://tempuri.org/ISCM/GetSuppliers", ReplyAction="http://tempuri.org/ISCM/GetSuppliersResponse")]
        DataTable GetSuppliers(Session us);
        
        [OperationContract(Action="http://tempuri.org/ISCM/GetSupplierInfo", ReplyAction="http://tempuri.org/ISCM/GetSupplierInfoResponse")]
        DataTable GetSupplierInfo(Session us);
        
        [OperationContract(Action="http://tempuri.org/ISCM/GetSupplier", ReplyAction="http://tempuri.org/ISCM/GetSupplierResponse")]
        MDG_Supplier GetSupplier(Session us, Guid id);
        
        [OperationContract(Action="http://tempuri.org/ISCM/AddMasterData", ReplyAction="http://tempuri.org/ISCM/AddMasterDataResponse")]
        bool AddMasterData(Session us, MasterData m, MDG_Supplier d);
        
        [OperationContract(Action="http://tempuri.org/ISCM/UpdateMasterData", ReplyAction="http://tempuri.org/ISCM/UpdateMasterDataResponse")]
        bool UpdateMasterData(Session us, MasterData m, MDG_Supplier d);
    }
    
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    internal interface ISCMChannel : ISCM, IClientChannel {
    }
    
    [DebuggerStepThrough()]
    [GeneratedCode("System.ServiceModel", "4.0.0.0")]
    internal partial class SCMClient : ClientBase<ISCM>, ISCM {
        
        public SCMClient() {
        }
        
        public SCMClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SCMClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SCMClient(string endpointConfigurationName, EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SCMClient(Binding binding, EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DataTable GetSuppliers(Session us) {
            return base.Channel.GetSuppliers(us);
        }
        
        public DataTable GetSupplierInfo(Session us) {
            return base.Channel.GetSupplierInfo(us);
        }
        
        public MDG_Supplier GetSupplier(Session us, Guid id) {
            return base.Channel.GetSupplier(us, id);
        }
        
        public bool AddMasterData(Session us, MasterData m, MDG_Supplier d) {
            return base.Channel.AddMasterData(us, m, d);
        }
        
        public bool UpdateMasterData(Session us, MasterData m, MDG_Supplier d) {
            return base.Channel.UpdateMasterData(us, m, d);
        }
    }
}
