//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight.WS.Server.Common.XFB
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    
    public partial class t_order_info
    {
    	[DataMember]
        public int id { get; set; }
    	[DataMember]
        public int owner_userid { get; set; }
    	[DataMember]
        public string order_name { get; set; }
    	[DataMember]
        public string product_name { get; set; }
    	[DataMember]
        public Nullable<float> product_price { get; set; }
    	[DataMember]
        public string shop_name { get; set; }
    	[DataMember]
        public Nullable<float> use_limit { get; set; }
    	[DataMember]
        public Nullable<int> order_status { get; set; }
    	[DataMember]
        public Nullable<int> create_userid { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> create_time { get; set; }
    	[DataMember]
        public Nullable<int> update_userid { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> update_time { get; set; }
    	[DataMember]
        public string description { get; set; }
    	[DataMember]
        public Nullable<int> stage_plan { get; set; }
    	[DataMember]
        public Nullable<float> first_pay { get; set; }
    	[DataMember]
        public Nullable<int> delete_flag { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> deal_time { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> cancel_time { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> refund_time { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> payoff_time { get; set; }
    	[DataMember]
        public Nullable<int> first_pay_channel { get; set; }
    	[DataMember]
        public string product_pic { get; set; }
    	[DataMember]
        public Nullable<int> isPay { get; set; }
    	[DataMember]
        public Nullable<float> all_stage_amout { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> return_time { get; set; }
    	[DataMember]
        public string return_cause { get; set; }
    }
}
