//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight.WS.Server.Common.XFB
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    
    public partial class t_score_log
    {
    	[DataMember]
        public int id { get; set; }
    	[DataMember]
        public Nullable<int> user_id { get; set; }
    	[DataMember]
        public Nullable<int> score { get; set; }
    	[DataMember]
        public Nullable<int> verify_userid { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> verify_time { get; set; }
    	[DataMember]
        public string flag { get; set; }
    	[DataMember]
        public string remarks { get; set; }
    }
}
