//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight.WS.Server.Common.XFB
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(t_bank_card_info))]
    [KnownType(typeof(t_category_info))]
    [KnownType(typeof(t_contact_info))]
    [KnownType(typeof(t_image_info))]
    [KnownType(typeof(t_job_info))]
    [KnownType(typeof(t_member_info))]
    [KnownType(typeof(t_model_info))]
    [KnownType(typeof(t_verify_quota))]
    [KnownType(typeof(t_verify_log))]
    [KnownType(typeof(t_student_info))]
    
    public partial class t_sys_user
    {
        public t_sys_user()
        {
            this.t_bank_card_info = new HashSet<t_bank_card_info>();
            this.t_bank_card_info1 = new HashSet<t_bank_card_info>();
            this.t_category_info = new HashSet<t_category_info>();
            this.t_category_info1 = new HashSet<t_category_info>();
            this.t_contact_info = new HashSet<t_contact_info>();
            this.t_contact_info1 = new HashSet<t_contact_info>();
            this.t_image_info = new HashSet<t_image_info>();
            this.t_image_info1 = new HashSet<t_image_info>();
            this.t_job_info = new HashSet<t_job_info>();
            this.t_job_info1 = new HashSet<t_job_info>();
            this.t_member_info = new HashSet<t_member_info>();
            this.t_member_info1 = new HashSet<t_member_info>();
            this.t_model_info = new HashSet<t_model_info>();
            this.t_verify_quota = new HashSet<t_verify_quota>();
            this.t_verify_log = new HashSet<t_verify_log>();
            this.t_verify_quota1 = new HashSet<t_verify_quota>();
            this.t_verify_log1 = new HashSet<t_verify_log>();
            this.t_student_info = new HashSet<t_student_info>();
            this.t_student_info1 = new HashSet<t_student_info>();
        }
    
    	[DataMember]
        public int id { get; set; }
    	[DataMember]
        public string login_name { get; set; }
    	[DataMember]
        public string real_name { get; set; }
    	[DataMember]
        public string pass_word { get; set; }
    	[DataMember]
        public Nullable<long> status { get; set; }
    	[DataMember]
        public string my_code { get; set; }
    	[DataMember]
        public string recom_code { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> create_time { get; set; }
    	[DataMember]
        public Nullable<int> create_userid { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> update_time { get; set; }
    	[DataMember]
        public Nullable<int> update_userid { get; set; }
    	[DataMember]
        public string description { get; set; }
    	[DataMember]
        public int recom_num { get; set; }
    	[DataMember]
        public string type { get; set; }
    	[DataMember]
        public string verify_state { get; set; }
    	[DataMember]
        public string has_verify { get; set; }
    
    	[DataMember]
        public virtual ICollection<t_bank_card_info> t_bank_card_info { get; set; }
    	[DataMember]
        public virtual ICollection<t_bank_card_info> t_bank_card_info1 { get; set; }
    	[DataMember]
        public virtual ICollection<t_category_info> t_category_info { get; set; }
    	[DataMember]
        public virtual ICollection<t_category_info> t_category_info1 { get; set; }
    	[DataMember]
        public virtual ICollection<t_contact_info> t_contact_info { get; set; }
    	[DataMember]
        public virtual ICollection<t_contact_info> t_contact_info1 { get; set; }
    	[DataMember]
        public virtual ICollection<t_image_info> t_image_info { get; set; }
    	[DataMember]
        public virtual ICollection<t_image_info> t_image_info1 { get; set; }
    	[DataMember]
        public virtual ICollection<t_job_info> t_job_info { get; set; }
    	[DataMember]
        public virtual ICollection<t_job_info> t_job_info1 { get; set; }
    	[DataMember]
        public virtual ICollection<t_member_info> t_member_info { get; set; }
    	[DataMember]
        public virtual ICollection<t_member_info> t_member_info1 { get; set; }
    	[DataMember]
        public virtual ICollection<t_model_info> t_model_info { get; set; }
    	[DataMember]
        public virtual ICollection<t_verify_quota> t_verify_quota { get; set; }
    	[DataMember]
        public virtual ICollection<t_verify_log> t_verify_log { get; set; }
    	[DataMember]
        public virtual ICollection<t_verify_quota> t_verify_quota1 { get; set; }
    	[DataMember]
        public virtual ICollection<t_verify_log> t_verify_log1 { get; set; }
    	[DataMember]
        public virtual ICollection<t_student_info> t_student_info { get; set; }
    	[DataMember]
        public virtual ICollection<t_student_info> t_student_info1 { get; set; }
    }
}
