//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight.WS.Server.Common.XFB
{
    using System;
    using System.Data.Entity.Core.Objects;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class XFBEntities : DbContext
    {
    	public XFBEntities()
            : this(false) { }
    
        public XFBEntities(bool proxyCreationEnabled)
            : base("name=XFBEntities")
        {
    		        this.Configuration.ProxyCreationEnabled = proxyCreationEnabled;
        }
    	
        public XFBEntities(string connectionString)
          : this(connectionString, false) { }
    	  
        public XFBEntities(string connectionString, bool proxyCreationEnabled)
            : base(connectionString)
        {
    		        this.Configuration.ProxyCreationEnabled = proxyCreationEnabled;
        }	
    	
        public ObjectContext ObjectContext
        {
          get { return ((IObjectContextAdapter)this).ObjectContext; }
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<t_bank_card_info> t_bank_card_info { get; set; }
        public virtual DbSet<t_bill_stage> t_bill_stage { get; set; }
        public virtual DbSet<t_category_info> t_category_info { get; set; }
        public virtual DbSet<t_contact_info> t_contact_info { get; set; }
        public virtual DbSet<t_credit_sesame> t_credit_sesame { get; set; }
        public virtual DbSet<t_image_info> t_image_info { get; set; }
        public virtual DbSet<t_job_info> t_job_info { get; set; }
        public virtual DbSet<t_member_info> t_member_info { get; set; }
        public virtual DbSet<t_model_info> t_model_info { get; set; }
        public virtual DbSet<t_quota_score> t_quota_score { get; set; }
        public virtual DbSet<t_score_log> t_score_log { get; set; }
        public virtual DbSet<t_student_info> t_student_info { get; set; }
        public virtual DbSet<t_sys_user> t_sys_user { get; set; }
        public virtual DbSet<t_verify_log> t_verify_log { get; set; }
        public virtual DbSet<t_verify_quota> t_verify_quota { get; set; }
        public virtual DbSet<t_order_info> t_order_info { get; set; }
        public virtual DbSet<t_mysql_seq> t_mysql_seq { get; set; }
        public virtual DbSet<t_interface_log> t_interface_log { get; set; }
    }
}
