USE [Insight_WS]
GO

/****** Object:  StoredProcedure [dbo].[USP_BAZAAR_REGISTER]    Script Date: 2015-08-18 11:11:32 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




-- =============================================
-- AUTHOR:		XIANGQIAN,WU
-- CREATE DATE: 2015-7-29 15:41
-- DESCRIPTION:	市场版注册
-- =============================================
CREATE PROCEDURE [dbo].[USP_BAZAAR_REGISTER]
	-- ADD THE PARAMETERS FOR THE STORED PROCEDURE HERE
	@NAME NVARCHAR(64),	--1 姓名
	@ALIAS NVARCHAR(32),  --2 手机号
	@PASSWORD VARCHAR(50),  --3 密码
	@TYPE VARCHAR(32),      --4 类型固定值-1
	@IDCARDNO VARCHAR(18),  --5 身份证号
	@CREATORUSERID UNIQUEIDENTIFIER --6 固定值 GUID 00000000-0000-0000-0000-000000000000
AS
DECLARE @MID UNIQUEIDENTIFIER --MASTERDATA GUID
DECLARE @OUTPUT VARCHAR(200) --输出
SET @OUTPUT = 'NAME='+@NAME+'----ALIAS='+@ALIAS+'----PASSWORD='+@PASSWORD+'----TYPE='+@TYPE+'----IDCARDNO='+@IDCARDNO+'----CREATORUSERID='+CONVERT(CHAR(255), @CREATORUSERID)-- INIT
BEGIN
	-- SET NOCOUNT ON ADDED TO PREVENT EXTRA RESULT SETS FROM
	-- INTERFERING WITH SELECT STATEMENTS.
	SET NOCOUNT ON;
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
	--打印参数
	PRINT @OUTPUT
	-- TRY EXCEPTION
	BEGIN TRY
	--BEGIN TRANSACTION
	BEGIN TRAN TRAN_STAT_NUMBER

	INSERT MASTERDATA (NAME, ALIAS) SELECT @NAME, @ALIAS 
	
	SELECT @MID=ID FROM MASTERDATA WHERE SN = SCOPE_IDENTITY()

	INSERT SYS_USER (ID, NAME, LOGINNAME, PASSWORD, TYPE, CREATORUSERID) SELECT @MID, @NAME, @ALIAS, @PASSWORD, @TYPE, @CREATORUSERID

	INSERT MDG_ENTMEMBER (MID,IDCARDNO) SELECT @MID,@IDCARDNO

	--打印ID
	PRINT '----MID='+CONVERT(CHAR(255), @MID)
 --  COMMIT TRANSACTION WHEN THIS TRANSACTION HAS NOT ERROR
	COMMIT TRAN TRAN_STAT_NUMBER
	END TRY 
	BEGIN CATCH 
			--THORWS ERROR 
			 RAISERROR('OUTPUT IS {%S} ERROR OF  DATA TARNSFER',16,2,@OUTPUT)
			 RAISERROR('MOBILE IS {%S} ERROR OF  DATA TARNSFER',16,2,@ALIAS)
			 --ROLLBACK TRANSACTION 
			 ROLLBACK TRAN TRAN_STAT_NUMBER
	END CATCH 
	--RETURN()
END



GO


