//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight.WS.Client.XinFenBao.Service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Service.IManager")]
    internal interface IManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManager/GetCheckListDate", ReplyAction="http://tempuri.org/IManager/GetCheckListDateResponse")]
        System.Data.DataTable GetCheckListDate(Insight.WS.Client.Common.Service.Session us);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManager/GetCheckListForDate", ReplyAction="http://tempuri.org/IManager/GetCheckListForDateResponse")]
        System.Data.DataTable GetCheckListForDate(Insight.WS.Client.Common.Service.Session us, string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManager/GetCheckListForName", ReplyAction="http://tempuri.org/IManager/GetCheckListForNameResponse")]
        System.Data.DataTable GetCheckListForName(Insight.WS.Client.Common.Service.Session us, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManager/GetAuditList", ReplyAction="http://tempuri.org/IManager/GetAuditListResponse")]
        System.Data.DataTable GetAuditList(Insight.WS.Client.Common.Service.Session us);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManager/GetFeedbackDate", ReplyAction="http://tempuri.org/IManager/GetFeedbackDateResponse")]
        System.Data.DataTable GetFeedbackDate(Insight.WS.Client.Common.Service.Session us);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManager/GetFeedBacksForDate", ReplyAction="http://tempuri.org/IManager/GetFeedBacksForDateResponse")]
        System.Data.DataTable GetFeedBacksForDate(Insight.WS.Client.Common.Service.Session us, string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManager/GetFeedBacksForName", ReplyAction="http://tempuri.org/IManager/GetFeedBacksForNameResponse")]
        System.Data.DataTable GetFeedBacksForName(Insight.WS.Client.Common.Service.Session us, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManager/GetFeedback", ReplyAction="http://tempuri.org/IManager/GetFeedbackResponse")]
        Insight.WS.Client.Common.Service.MDE_Member_Feedback GetFeedback(Insight.WS.Client.Common.Service.Session us, System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManager/SaveReply", ReplyAction="http://tempuri.org/IManager/SaveReplyResponse")]
        bool SaveReply(Insight.WS.Client.Common.Service.Session us, Insight.WS.Client.Common.Service.MDE_Member_Feedback obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManager/Pigeonhole", ReplyAction="http://tempuri.org/IManager/PigeonholeResponse")]
        bool Pigeonhole(Insight.WS.Client.Common.Service.Session us, Insight.WS.Client.Common.Service.MDE_Member_Feedback obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManager/GetStagePlans", ReplyAction="http://tempuri.org/IManager/GetStagePlansResponse")]
        System.Collections.Generic.List<Insight.WS.Client.Common.Service.BIZ_StagePlan> GetStagePlans(Insight.WS.Client.Common.Service.Session us);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManager/AddStagePlan", ReplyAction="http://tempuri.org/IManager/AddStagePlanResponse")]
        bool AddStagePlan(Insight.WS.Client.Common.Service.Session us, Insight.WS.Client.Common.Service.BIZ_StagePlan obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManager/SetDefault", ReplyAction="http://tempuri.org/IManager/SetDefaultResponse")]
        bool SetDefault(Insight.WS.Client.Common.Service.Session us, System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManager/DeletePlan", ReplyAction="http://tempuri.org/IManager/DeletePlanResponse")]
        bool DeletePlan(Insight.WS.Client.Common.Service.Session us, System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManager/GetAdvertisers", ReplyAction="http://tempuri.org/IManager/GetAdvertisersResponse")]
        System.Collections.Generic.List<Insight.WS.Client.Common.Service.BIZ_Advertiser> GetAdvertisers(Insight.WS.Client.Common.Service.Session us);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManager/AddAdvertiser", ReplyAction="http://tempuri.org/IManager/AddAdvertiserResponse")]
        bool AddAdvertiser(Insight.WS.Client.Common.Service.Session us, Insight.WS.Client.Common.Service.BIZ_Advertiser obj, byte[] img);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManager/EditAdvertiser", ReplyAction="http://tempuri.org/IManager/EditAdvertiserResponse")]
        bool EditAdvertiser(Insight.WS.Client.Common.Service.Session us, Insight.WS.Client.Common.Service.BIZ_Advertiser obj, byte[] img);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IManager/DelAdvertiser", ReplyAction="http://tempuri.org/IManager/DelAdvertiserResponse")]
        bool DelAdvertiser(Insight.WS.Client.Common.Service.Session us, System.Guid id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface IManagerChannel : Insight.WS.Client.XinFenBao.Service.IManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class ManagerClient : System.ServiceModel.ClientBase<Insight.WS.Client.XinFenBao.Service.IManager>, Insight.WS.Client.XinFenBao.Service.IManager {
        
        public ManagerClient() {
        }
        
        public ManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable GetCheckListDate(Insight.WS.Client.Common.Service.Session us) {
            return base.Channel.GetCheckListDate(us);
        }
        
        public System.Data.DataTable GetCheckListForDate(Insight.WS.Client.Common.Service.Session us, string date) {
            return base.Channel.GetCheckListForDate(us, date);
        }
        
        public System.Data.DataTable GetCheckListForName(Insight.WS.Client.Common.Service.Session us, string name) {
            return base.Channel.GetCheckListForName(us, name);
        }
        
        public System.Data.DataTable GetAuditList(Insight.WS.Client.Common.Service.Session us) {
            return base.Channel.GetAuditList(us);
        }
        
        public System.Data.DataTable GetFeedbackDate(Insight.WS.Client.Common.Service.Session us) {
            return base.Channel.GetFeedbackDate(us);
        }
        
        public System.Data.DataTable GetFeedBacksForDate(Insight.WS.Client.Common.Service.Session us, string date) {
            return base.Channel.GetFeedBacksForDate(us, date);
        }
        
        public System.Data.DataTable GetFeedBacksForName(Insight.WS.Client.Common.Service.Session us, string name) {
            return base.Channel.GetFeedBacksForName(us, name);
        }
        
        public Insight.WS.Client.Common.Service.MDE_Member_Feedback GetFeedback(Insight.WS.Client.Common.Service.Session us, System.Guid id) {
            return base.Channel.GetFeedback(us, id);
        }
        
        public bool SaveReply(Insight.WS.Client.Common.Service.Session us, Insight.WS.Client.Common.Service.MDE_Member_Feedback obj) {
            return base.Channel.SaveReply(us, obj);
        }
        
        public bool Pigeonhole(Insight.WS.Client.Common.Service.Session us, Insight.WS.Client.Common.Service.MDE_Member_Feedback obj) {
            return base.Channel.Pigeonhole(us, obj);
        }
        
        public System.Collections.Generic.List<Insight.WS.Client.Common.Service.BIZ_StagePlan> GetStagePlans(Insight.WS.Client.Common.Service.Session us) {
            return base.Channel.GetStagePlans(us);
        }
        
        public bool AddStagePlan(Insight.WS.Client.Common.Service.Session us, Insight.WS.Client.Common.Service.BIZ_StagePlan obj) {
            return base.Channel.AddStagePlan(us, obj);
        }
        
        public bool SetDefault(Insight.WS.Client.Common.Service.Session us, System.Guid id) {
            return base.Channel.SetDefault(us, id);
        }
        
        public bool DeletePlan(Insight.WS.Client.Common.Service.Session us, System.Guid id) {
            return base.Channel.DeletePlan(us, id);
        }
        
        public System.Collections.Generic.List<Insight.WS.Client.Common.Service.BIZ_Advertiser> GetAdvertisers(Insight.WS.Client.Common.Service.Session us) {
            return base.Channel.GetAdvertisers(us);
        }
        
        public bool AddAdvertiser(Insight.WS.Client.Common.Service.Session us, Insight.WS.Client.Common.Service.BIZ_Advertiser obj, byte[] img) {
            return base.Channel.AddAdvertiser(us, obj, img);
        }
        
        public bool EditAdvertiser(Insight.WS.Client.Common.Service.Session us, Insight.WS.Client.Common.Service.BIZ_Advertiser obj, byte[] img) {
            return base.Channel.EditAdvertiser(us, obj, img);
        }
        
        public bool DelAdvertiser(Insight.WS.Client.Common.Service.Session us, System.Guid id) {
            return base.Channel.DelAdvertiser(us, id);
        }
    }
}
