//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insight.WS.Client.MasterDatas.Service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Service.IMasterDatas")]
    internal interface IMasterDatas {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterDatas/GetDictionarys", ReplyAction="http://tempuri.org/IMasterDatas/GetDictionarysResponse")]
        System.Data.DataTable GetDictionarys(Insight.WS.Client.Common.Service.Session us);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterDatas/GetDictionary", ReplyAction="http://tempuri.org/IMasterDatas/GetDictionaryResponse")]
        Insight.WS.Client.Common.Service.MDG_Dictionary GetDictionary(Insight.WS.Client.Common.Service.Session us, System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterDatas/AddDictionary", ReplyAction="http://tempuri.org/IMasterDatas/AddDictionaryResponse")]
        bool AddDictionary(Insight.WS.Client.Common.Service.Session us, Insight.WS.Client.Common.Service.MasterData m, Insight.WS.Client.Common.Service.MDG_Dictionary d, int i);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterDatas/UpdateDictionary", ReplyAction="http://tempuri.org/IMasterDatas/UpdateDictionaryResponse")]
        bool UpdateDictionary(Insight.WS.Client.Common.Service.Session us, Insight.WS.Client.Common.Service.MasterData m, Insight.WS.Client.Common.Service.MDG_Dictionary d, int i);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterDatas/DelDictionary", ReplyAction="http://tempuri.org/IMasterDatas/DelDictionaryResponse")]
        int DelDictionary(Insight.WS.Client.Common.Service.Session us, System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterDatas/GetEmployees", ReplyAction="http://tempuri.org/IMasterDatas/GetEmployeesResponse")]
        System.Data.DataTable GetEmployees(Insight.WS.Client.Common.Service.Session us, System.Guid oid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterDatas/GetEmployeesForName", ReplyAction="http://tempuri.org/IMasterDatas/GetEmployeesForNameResponse")]
        System.Data.DataTable GetEmployeesForName(Insight.WS.Client.Common.Service.Session us, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterDatas/GetEmployee", ReplyAction="http://tempuri.org/IMasterDatas/GetEmployeeResponse")]
        Insight.WS.Client.Common.Service.MDG_Employee GetEmployee(Insight.WS.Client.Common.Service.Session us, System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterDatas/GetEmployeeTitle", ReplyAction="http://tempuri.org/IMasterDatas/GetEmployeeTitleResponse")]
        Insight.WS.Client.Common.Service.MDR_ET GetEmployeeTitle(Insight.WS.Client.Common.Service.Session us, System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterDatas/AddEmployee", ReplyAction="http://tempuri.org/IMasterDatas/AddEmployeeResponse")]
        bool AddEmployee(Insight.WS.Client.Common.Service.Session us, Insight.WS.Client.Common.Service.MasterData m, Insight.WS.Client.Common.Service.MDG_Employee d, Insight.WS.Client.Common.Service.MDR_ET r, System.Data.DataTable cdt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterDatas/UpdateEmployee", ReplyAction="http://tempuri.org/IMasterDatas/UpdateEmployeeResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.Session))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.LoginResult))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.MDG_Dictionary))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.ABS_Advance>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.ABS_Advance))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.ABS_Advance_Detail>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.ABS_Advance_Detail))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.ABS_Advance_Record>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.ABS_Advance_Record))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.ABS_Clearing))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.ABS_Clearing_Attachs>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.ABS_Clearing_Attachs))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.ImageData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.ABS_Clearing_Check>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.ABS_Clearing_Check))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.ABS_Clearing>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_Organization))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.ABS_Contract>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.ABS_Contract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.ABS_Contract_Attachs>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.ABS_Contract_Attachs))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.MasterData))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.ABS_Clearing_Item>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.ABS_Clearing_Item))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.ABS_Clearing_Pay>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.ABS_Clearing_Pay))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.ABS_StockDetail>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.ABS_StockDetail))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.ABS_StockCapital))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.ABS_Contract_FundPlan))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.ABS_Contract_FundPerform>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.ABS_Contract_FundPerform))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.ABS_Delivery))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.ABS_Contract_GoodsPerform>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.ABS_Contract_GoodsPerform))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.ABS_Contract_GoodsPlan))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.ABS_Contract_Subjects))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.ABS_Contract_FundPlan>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.ABS_Contract_GoodsPlan>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.BASE_Category))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.ABS_Contract_Subjects>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.ImageData>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.MDG_Customer>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.MDG_Customer))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_User))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.ABS_Delivery>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.ABS_Storage_Location>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.ABS_Storage_Location))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.ABS_Storage_Detail>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.ABS_Storage_Detail))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.ABS_Storage_Summary))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_Module))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.BASE_Category>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.MasterData_Property>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.MasterData_Property))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.MDD_Binary>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.MDD_Binary))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.MDD_Character))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.MDD_Date))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.MDD_Numeric))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_Allot_Record))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_Code_Scheme))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_Allot_Record>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_Code_Allot>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_Code_Allot))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.ABS_Delivery_Item))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_Code_Record))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.ABS_Delivery_Attachs))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_ModuleGroup))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_Module>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.MDG_Employee))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.MDG_Employee>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.MDR_ET>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.MDR_ET))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_ModuleAction))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_RolePerm_Action>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_RolePerm_Action))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_Role))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_Report_Member>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_Report_Member))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_Report_Entity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_Report_Definition))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_Report_Entity>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_Report_Instances>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_Report_Instances))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_Report_IU>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_Report_IU))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.MDG_Expense))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_Report_Period))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_Report_Rules))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_Report_Period>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_Report_Schedular>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_Report_Schedular))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.MDG_Material))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_Report_Templates))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_Report_Definition>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.MDG_Supplier))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.MDS_Contact_Info))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_Role_User))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_ModuleParam))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.MasterData_Merger))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_Role_UserGroup))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_UserGroup))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_Role_UserGroup>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_UserGroupMember>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_UserGroupMember))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_Role_Title))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_RolePerm_Data))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.MDG_Contact))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_RolePerm_DataAbs))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.MDR_MU))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_Alert_Rules))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_Alert_Message>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_Alert_Message))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_Alert_Send>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_Alert_Send))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_Alert_Target))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_OrgMember))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Insight.WS.Client.Common.Service.SYS_OrgMerger))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_Alert_Target>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_RolePerm_Data>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_RolePerm_DataAbs>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_Role_Title>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_Role_User>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_Code_Record>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.MDD_Character>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.MDD_Date>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.MDD_Numeric>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_ModuleAction>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_ModuleParam>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.MDG_Contact>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.MDG_Dictionary>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.MDG_Expense>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.MDG_Material>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.MDG_Supplier>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.MDR_MU>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.MasterData_Merger>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_Alert_Rules>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_Code_Scheme>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_OrgMember>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_OrgMerger>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_Organization>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_Report_Rules>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_Report_Templates>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_Role>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.SYS_UserGroup>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.MasterData>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.ABS_Delivery_Attachs>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.ABS_Delivery_Item>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.ABS_Storage_Summary>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.MDS_Contact_Info>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<Insight.WS.Client.Common.Service.ABS_StockCapital>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<object>))]
        bool UpdateEmployee(Insight.WS.Client.Common.Service.Session us, Insight.WS.Client.Common.Service.MasterData m, Insight.WS.Client.Common.Service.MDG_Employee d, Insight.WS.Client.Common.Service.MDR_ET r, System.Collections.Generic.List<object> cdl, System.Data.DataTable cdt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterDatas/UpdateStatus", ReplyAction="http://tempuri.org/IMasterDatas/UpdateStatusResponse")]
        bool UpdateStatus(Insight.WS.Client.Common.Service.Session us, System.Guid id, int stu);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterDatas/GetExpenses", ReplyAction="http://tempuri.org/IMasterDatas/GetExpensesResponse")]
        System.Data.DataTable GetExpenses(Insight.WS.Client.Common.Service.Session us);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterDatas/GetExpense", ReplyAction="http://tempuri.org/IMasterDatas/GetExpenseResponse")]
        Insight.WS.Client.Common.Service.MDG_Expense GetExpense(Insight.WS.Client.Common.Service.Session us, System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterDatas/AddExpense", ReplyAction="http://tempuri.org/IMasterDatas/AddExpenseResponse")]
        bool AddExpense(Insight.WS.Client.Common.Service.Session us, Insight.WS.Client.Common.Service.MasterData m, Insight.WS.Client.Common.Service.MDG_Expense d, int i);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterDatas/UpdateExpense", ReplyAction="http://tempuri.org/IMasterDatas/UpdateExpenseResponse")]
        bool UpdateExpense(Insight.WS.Client.Common.Service.Session us, Insight.WS.Client.Common.Service.MasterData m, Insight.WS.Client.Common.Service.MDG_Expense d, int i);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterDatas/DelExpense", ReplyAction="http://tempuri.org/IMasterDatas/DelExpenseResponse")]
        int DelExpense(Insight.WS.Client.Common.Service.Session us, System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterDatas/GetMaterials", ReplyAction="http://tempuri.org/IMasterDatas/GetMaterialsResponse")]
        System.Data.DataTable GetMaterials(Insight.WS.Client.Common.Service.Session us);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterDatas/GetMaterial", ReplyAction="http://tempuri.org/IMasterDatas/GetMaterialResponse")]
        Insight.WS.Client.Common.Service.MDG_Material GetMaterial(Insight.WS.Client.Common.Service.Session us, System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterDatas/AddMaterial", ReplyAction="http://tempuri.org/IMasterDatas/AddMaterialResponse")]
        bool AddMaterial(Insight.WS.Client.Common.Service.Session us, Insight.WS.Client.Common.Service.MasterData m, Insight.WS.Client.Common.Service.MDG_Material d, int i);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterDatas/UpdateMaterial", ReplyAction="http://tempuri.org/IMasterDatas/UpdateMaterialResponse")]
        bool UpdateMaterial(Insight.WS.Client.Common.Service.Session us, Insight.WS.Client.Common.Service.MasterData m, Insight.WS.Client.Common.Service.MDG_Material d, int i);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterDatas/DelMaterial", ReplyAction="http://tempuri.org/IMasterDatas/DelMaterialResponse")]
        int DelMaterial(Insight.WS.Client.Common.Service.Session us, System.Guid id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface IMasterDatasChannel : Insight.WS.Client.MasterDatas.Service.IMasterDatas, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class MasterDatasClient : System.ServiceModel.ClientBase<Insight.WS.Client.MasterDatas.Service.IMasterDatas>, Insight.WS.Client.MasterDatas.Service.IMasterDatas {
        
        public MasterDatasClient() {
        }
        
        public MasterDatasClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MasterDatasClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MasterDatasClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MasterDatasClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable GetDictionarys(Insight.WS.Client.Common.Service.Session us) {
            return base.Channel.GetDictionarys(us);
        }
        
        public Insight.WS.Client.Common.Service.MDG_Dictionary GetDictionary(Insight.WS.Client.Common.Service.Session us, System.Guid id) {
            return base.Channel.GetDictionary(us, id);
        }
        
        public bool AddDictionary(Insight.WS.Client.Common.Service.Session us, Insight.WS.Client.Common.Service.MasterData m, Insight.WS.Client.Common.Service.MDG_Dictionary d, int i) {
            return base.Channel.AddDictionary(us, m, d, i);
        }
        
        public bool UpdateDictionary(Insight.WS.Client.Common.Service.Session us, Insight.WS.Client.Common.Service.MasterData m, Insight.WS.Client.Common.Service.MDG_Dictionary d, int i) {
            return base.Channel.UpdateDictionary(us, m, d, i);
        }
        
        public int DelDictionary(Insight.WS.Client.Common.Service.Session us, System.Guid id) {
            return base.Channel.DelDictionary(us, id);
        }
        
        public System.Data.DataTable GetEmployees(Insight.WS.Client.Common.Service.Session us, System.Guid oid) {
            return base.Channel.GetEmployees(us, oid);
        }
        
        public System.Data.DataTable GetEmployeesForName(Insight.WS.Client.Common.Service.Session us, string name) {
            return base.Channel.GetEmployeesForName(us, name);
        }
        
        public Insight.WS.Client.Common.Service.MDG_Employee GetEmployee(Insight.WS.Client.Common.Service.Session us, System.Guid id) {
            return base.Channel.GetEmployee(us, id);
        }
        
        public Insight.WS.Client.Common.Service.MDR_ET GetEmployeeTitle(Insight.WS.Client.Common.Service.Session us, System.Guid id) {
            return base.Channel.GetEmployeeTitle(us, id);
        }
        
        public bool AddEmployee(Insight.WS.Client.Common.Service.Session us, Insight.WS.Client.Common.Service.MasterData m, Insight.WS.Client.Common.Service.MDG_Employee d, Insight.WS.Client.Common.Service.MDR_ET r, System.Data.DataTable cdt) {
            return base.Channel.AddEmployee(us, m, d, r, cdt);
        }
        
        public bool UpdateEmployee(Insight.WS.Client.Common.Service.Session us, Insight.WS.Client.Common.Service.MasterData m, Insight.WS.Client.Common.Service.MDG_Employee d, Insight.WS.Client.Common.Service.MDR_ET r, System.Collections.Generic.List<object> cdl, System.Data.DataTable cdt) {
            return base.Channel.UpdateEmployee(us, m, d, r, cdl, cdt);
        }
        
        public bool UpdateStatus(Insight.WS.Client.Common.Service.Session us, System.Guid id, int stu) {
            return base.Channel.UpdateStatus(us, id, stu);
        }
        
        public System.Data.DataTable GetExpenses(Insight.WS.Client.Common.Service.Session us) {
            return base.Channel.GetExpenses(us);
        }
        
        public Insight.WS.Client.Common.Service.MDG_Expense GetExpense(Insight.WS.Client.Common.Service.Session us, System.Guid id) {
            return base.Channel.GetExpense(us, id);
        }
        
        public bool AddExpense(Insight.WS.Client.Common.Service.Session us, Insight.WS.Client.Common.Service.MasterData m, Insight.WS.Client.Common.Service.MDG_Expense d, int i) {
            return base.Channel.AddExpense(us, m, d, i);
        }
        
        public bool UpdateExpense(Insight.WS.Client.Common.Service.Session us, Insight.WS.Client.Common.Service.MasterData m, Insight.WS.Client.Common.Service.MDG_Expense d, int i) {
            return base.Channel.UpdateExpense(us, m, d, i);
        }
        
        public int DelExpense(Insight.WS.Client.Common.Service.Session us, System.Guid id) {
            return base.Channel.DelExpense(us, id);
        }
        
        public System.Data.DataTable GetMaterials(Insight.WS.Client.Common.Service.Session us) {
            return base.Channel.GetMaterials(us);
        }
        
        public Insight.WS.Client.Common.Service.MDG_Material GetMaterial(Insight.WS.Client.Common.Service.Session us, System.Guid id) {
            return base.Channel.GetMaterial(us, id);
        }
        
        public bool AddMaterial(Insight.WS.Client.Common.Service.Session us, Insight.WS.Client.Common.Service.MasterData m, Insight.WS.Client.Common.Service.MDG_Material d, int i) {
            return base.Channel.AddMaterial(us, m, d, i);
        }
        
        public bool UpdateMaterial(Insight.WS.Client.Common.Service.Session us, Insight.WS.Client.Common.Service.MasterData m, Insight.WS.Client.Common.Service.MDG_Material d, int i) {
            return base.Channel.UpdateMaterial(us, m, d, i);
        }
        
        public int DelMaterial(Insight.WS.Client.Common.Service.Session us, System.Guid id) {
            return base.Channel.DelMaterial(us, id);
        }
    }
}
