IF EXISTS (SELECT * FROM sysobjects WHERE id = OBJECT_ID(N'Get_Price') AND OBJECTPROPERTY(id, N'ISSCALARFUNCTION') = 1)
DROP FUNCTION Get_Price
GO


/*****标量值函数：获取物资/费用的单价*****/

CREATE FUNCTION Get_Price (
@SubjectId           UNIQUEIDENTIFIER    --物资/费用ID
)

RETURNS DECIMAL(20,4) AS
BEGIN


RETURN 100.000

END
GO